// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: player.proto

package mirrorWar.player;

public final class Player {
  private Player() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PlayerStateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mirrorWar.player.PlayerState)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required uint32 id = 1;</code>
     */
    int getId();

    /**
     * <code>required .mirrorWar.player.PlayerState.Color color = 2;</code>
     */
    boolean hasColor();
    /**
     * <code>required .mirrorWar.player.PlayerState.Color color = 2;</code>
     */
    mirrorWar.player.Player.PlayerState.Color getColor();

    /**
     * <code>required double x = 3;</code>
     */
    boolean hasX();
    /**
     * <code>required double x = 3;</code>
     */
    double getX();

    /**
     * <code>required double y = 4;</code>
     */
    boolean hasY();
    /**
     * <code>required double y = 4;</code>
     */
    double getY();

    /**
     * <code>required .mirrorWar.player.PlayerState.Animation animation = 5;</code>
     */
    boolean hasAnimation();
    /**
     * <code>required .mirrorWar.player.PlayerState.Animation animation = 5;</code>
     */
    mirrorWar.player.Player.PlayerState.Animation getAnimation();

    /**
     * <code>required .mirrorWar.player.PlayerState.Facing facing = 6;</code>
     */
    boolean hasFacing();
    /**
     * <code>required .mirrorWar.player.PlayerState.Facing facing = 6;</code>
     */
    mirrorWar.player.Player.PlayerState.Facing getFacing();
  }
  /**
   * Protobuf type {@code mirrorWar.player.PlayerState}
   */
  public  static final class PlayerState extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:mirrorWar.player.PlayerState)
      PlayerStateOrBuilder {
    // Use PlayerState.newBuilder() to construct.
    private PlayerState(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PlayerState() {
      id_ = 0;
      color_ = 1;
      x_ = 0D;
      y_ = 0D;
      animation_ = 1;
      facing_ = 1;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PlayerState(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readUInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              mirrorWar.player.Player.PlayerState.Color value = mirrorWar.player.Player.PlayerState.Color.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                color_ = rawValue;
              }
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              x_ = input.readDouble();
              break;
            }
            case 33: {
              bitField0_ |= 0x00000008;
              y_ = input.readDouble();
              break;
            }
            case 40: {
              int rawValue = input.readEnum();
              mirrorWar.player.Player.PlayerState.Animation value = mirrorWar.player.Player.PlayerState.Animation.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(5, rawValue);
              } else {
                bitField0_ |= 0x00000010;
                animation_ = rawValue;
              }
              break;
            }
            case 48: {
              int rawValue = input.readEnum();
              mirrorWar.player.Player.PlayerState.Facing value = mirrorWar.player.Player.PlayerState.Facing.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(6, rawValue);
              } else {
                bitField0_ |= 0x00000020;
                facing_ = rawValue;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mirrorWar.player.Player.internal_static_mirrorWar_player_PlayerState_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mirrorWar.player.Player.internal_static_mirrorWar_player_PlayerState_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              mirrorWar.player.Player.PlayerState.class, mirrorWar.player.Player.PlayerState.Builder.class);
    }

    /**
     * Protobuf enum {@code mirrorWar.player.PlayerState.Animation}
     */
    public enum Animation
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>STANDING = 1;</code>
       */
      STANDING(1),
      /**
       * <code>WALKING = 2;</code>
       */
      WALKING(2),
      /**
       * <code>RUNNING = 3;</code>
       */
      RUNNING(3),
      /**
       * <code>KILLED = 4;</code>
       */
      KILLED(4),
      ;

      /**
       * <code>STANDING = 1;</code>
       */
      public static final int STANDING_VALUE = 1;
      /**
       * <code>WALKING = 2;</code>
       */
      public static final int WALKING_VALUE = 2;
      /**
       * <code>RUNNING = 3;</code>
       */
      public static final int RUNNING_VALUE = 3;
      /**
       * <code>KILLED = 4;</code>
       */
      public static final int KILLED_VALUE = 4;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Animation valueOf(int value) {
        return forNumber(value);
      }

      public static Animation forNumber(int value) {
        switch (value) {
          case 1: return STANDING;
          case 2: return WALKING;
          case 3: return RUNNING;
          case 4: return KILLED;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Animation>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Animation> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Animation>() {
              public Animation findValueByNumber(int number) {
                return Animation.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return mirrorWar.player.Player.PlayerState.getDescriptor().getEnumTypes().get(0);
      }

      private static final Animation[] VALUES = values();

      public static Animation valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Animation(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:mirrorWar.player.PlayerState.Animation)
    }

    /**
     * Protobuf enum {@code mirrorWar.player.PlayerState.Facing}
     */
    public enum Facing
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>LEFT = 1;</code>
       */
      LEFT(1),
      /**
       * <code>RIGHT = 2;</code>
       */
      RIGHT(2),
      ;

      /**
       * <code>LEFT = 1;</code>
       */
      public static final int LEFT_VALUE = 1;
      /**
       * <code>RIGHT = 2;</code>
       */
      public static final int RIGHT_VALUE = 2;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Facing valueOf(int value) {
        return forNumber(value);
      }

      public static Facing forNumber(int value) {
        switch (value) {
          case 1: return LEFT;
          case 2: return RIGHT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Facing>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Facing> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Facing>() {
              public Facing findValueByNumber(int number) {
                return Facing.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return mirrorWar.player.Player.PlayerState.getDescriptor().getEnumTypes().get(1);
      }

      private static final Facing[] VALUES = values();

      public static Facing valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Facing(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:mirrorWar.player.PlayerState.Facing)
    }

    /**
     * Protobuf enum {@code mirrorWar.player.PlayerState.Color}
     */
    public enum Color
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>RED = 1;</code>
       */
      RED(1),
      /**
       * <code>BLUE = 2;</code>
       */
      BLUE(2),
      /**
       * <code>ORANGE = 3;</code>
       */
      ORANGE(3),
      ;

      /**
       * <code>RED = 1;</code>
       */
      public static final int RED_VALUE = 1;
      /**
       * <code>BLUE = 2;</code>
       */
      public static final int BLUE_VALUE = 2;
      /**
       * <code>ORANGE = 3;</code>
       */
      public static final int ORANGE_VALUE = 3;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Color valueOf(int value) {
        return forNumber(value);
      }

      public static Color forNumber(int value) {
        switch (value) {
          case 1: return RED;
          case 2: return BLUE;
          case 3: return ORANGE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Color>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Color> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Color>() {
              public Color findValueByNumber(int number) {
                return Color.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return mirrorWar.player.Player.PlayerState.getDescriptor().getEnumTypes().get(2);
      }

      private static final Color[] VALUES = values();

      public static Color valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Color(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:mirrorWar.player.PlayerState.Color)
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required uint32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int COLOR_FIELD_NUMBER = 2;
    private int color_;
    /**
     * <code>required .mirrorWar.player.PlayerState.Color color = 2;</code>
     */
    public boolean hasColor() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .mirrorWar.player.PlayerState.Color color = 2;</code>
     */
    public mirrorWar.player.Player.PlayerState.Color getColor() {
      mirrorWar.player.Player.PlayerState.Color result = mirrorWar.player.Player.PlayerState.Color.valueOf(color_);
      return result == null ? mirrorWar.player.Player.PlayerState.Color.RED : result;
    }

    public static final int X_FIELD_NUMBER = 3;
    private double x_;
    /**
     * <code>required double x = 3;</code>
     */
    public boolean hasX() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required double x = 3;</code>
     */
    public double getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 4;
    private double y_;
    /**
     * <code>required double y = 4;</code>
     */
    public boolean hasY() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required double y = 4;</code>
     */
    public double getY() {
      return y_;
    }

    public static final int ANIMATION_FIELD_NUMBER = 5;
    private int animation_;
    /**
     * <code>required .mirrorWar.player.PlayerState.Animation animation = 5;</code>
     */
    public boolean hasAnimation() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required .mirrorWar.player.PlayerState.Animation animation = 5;</code>
     */
    public mirrorWar.player.Player.PlayerState.Animation getAnimation() {
      mirrorWar.player.Player.PlayerState.Animation result = mirrorWar.player.Player.PlayerState.Animation.valueOf(animation_);
      return result == null ? mirrorWar.player.Player.PlayerState.Animation.STANDING : result;
    }

    public static final int FACING_FIELD_NUMBER = 6;
    private int facing_;
    /**
     * <code>required .mirrorWar.player.PlayerState.Facing facing = 6;</code>
     */
    public boolean hasFacing() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required .mirrorWar.player.PlayerState.Facing facing = 6;</code>
     */
    public mirrorWar.player.Player.PlayerState.Facing getFacing() {
      mirrorWar.player.Player.PlayerState.Facing result = mirrorWar.player.Player.PlayerState.Facing.valueOf(facing_);
      return result == null ? mirrorWar.player.Player.PlayerState.Facing.LEFT : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasColor()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasX()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasY()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAnimation()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFacing()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, color_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, x_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeDouble(4, y_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeEnum(5, animation_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeEnum(6, facing_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, color_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, x_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, y_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, animation_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, facing_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof mirrorWar.player.Player.PlayerState)) {
        return super.equals(obj);
      }
      mirrorWar.player.Player.PlayerState other = (mirrorWar.player.Player.PlayerState) obj;

      boolean result = true;
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && (getId()
            == other.getId());
      }
      result = result && (hasColor() == other.hasColor());
      if (hasColor()) {
        result = result && color_ == other.color_;
      }
      result = result && (hasX() == other.hasX());
      if (hasX()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getX())
            == java.lang.Double.doubleToLongBits(
                other.getX()));
      }
      result = result && (hasY() == other.hasY());
      if (hasY()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getY())
            == java.lang.Double.doubleToLongBits(
                other.getY()));
      }
      result = result && (hasAnimation() == other.hasAnimation());
      if (hasAnimation()) {
        result = result && animation_ == other.animation_;
      }
      result = result && (hasFacing() == other.hasFacing());
      if (hasFacing()) {
        result = result && facing_ == other.facing_;
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
      }
      if (hasColor()) {
        hash = (37 * hash) + COLOR_FIELD_NUMBER;
        hash = (53 * hash) + color_;
      }
      if (hasX()) {
        hash = (37 * hash) + X_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getX()));
      }
      if (hasY()) {
        hash = (37 * hash) + Y_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getY()));
      }
      if (hasAnimation()) {
        hash = (37 * hash) + ANIMATION_FIELD_NUMBER;
        hash = (53 * hash) + animation_;
      }
      if (hasFacing()) {
        hash = (37 * hash) + FACING_FIELD_NUMBER;
        hash = (53 * hash) + facing_;
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static mirrorWar.player.Player.PlayerState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mirrorWar.player.Player.PlayerState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mirrorWar.player.Player.PlayerState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mirrorWar.player.Player.PlayerState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mirrorWar.player.Player.PlayerState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mirrorWar.player.Player.PlayerState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static mirrorWar.player.Player.PlayerState parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static mirrorWar.player.Player.PlayerState parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static mirrorWar.player.Player.PlayerState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mirrorWar.player.Player.PlayerState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(mirrorWar.player.Player.PlayerState prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mirrorWar.player.PlayerState}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:mirrorWar.player.PlayerState)
        mirrorWar.player.Player.PlayerStateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return mirrorWar.player.Player.internal_static_mirrorWar_player_PlayerState_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return mirrorWar.player.Player.internal_static_mirrorWar_player_PlayerState_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                mirrorWar.player.Player.PlayerState.class, mirrorWar.player.Player.PlayerState.Builder.class);
      }

      // Construct using mirrorWar.player.Player.PlayerState.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        color_ = 1;
        bitField0_ = (bitField0_ & ~0x00000002);
        x_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        y_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000008);
        animation_ = 1;
        bitField0_ = (bitField0_ & ~0x00000010);
        facing_ = 1;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return mirrorWar.player.Player.internal_static_mirrorWar_player_PlayerState_descriptor;
      }

      public mirrorWar.player.Player.PlayerState getDefaultInstanceForType() {
        return mirrorWar.player.Player.PlayerState.getDefaultInstance();
      }

      public mirrorWar.player.Player.PlayerState build() {
        mirrorWar.player.Player.PlayerState result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public mirrorWar.player.Player.PlayerState buildPartial() {
        mirrorWar.player.Player.PlayerState result = new mirrorWar.player.Player.PlayerState(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.color_ = color_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.x_ = x_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.y_ = y_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.animation_ = animation_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.facing_ = facing_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof mirrorWar.player.Player.PlayerState) {
          return mergeFrom((mirrorWar.player.Player.PlayerState)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(mirrorWar.player.Player.PlayerState other) {
        if (other == mirrorWar.player.Player.PlayerState.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasColor()) {
          setColor(other.getColor());
        }
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        if (other.hasAnimation()) {
          setAnimation(other.getAnimation());
        }
        if (other.hasFacing()) {
          setFacing(other.getFacing());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          return false;
        }
        if (!hasColor()) {
          return false;
        }
        if (!hasX()) {
          return false;
        }
        if (!hasY()) {
          return false;
        }
        if (!hasAnimation()) {
          return false;
        }
        if (!hasFacing()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        mirrorWar.player.Player.PlayerState parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (mirrorWar.player.Player.PlayerState) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required uint32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required uint32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private int color_ = 1;
      /**
       * <code>required .mirrorWar.player.PlayerState.Color color = 2;</code>
       */
      public boolean hasColor() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .mirrorWar.player.PlayerState.Color color = 2;</code>
       */
      public mirrorWar.player.Player.PlayerState.Color getColor() {
        mirrorWar.player.Player.PlayerState.Color result = mirrorWar.player.Player.PlayerState.Color.valueOf(color_);
        return result == null ? mirrorWar.player.Player.PlayerState.Color.RED : result;
      }
      /**
       * <code>required .mirrorWar.player.PlayerState.Color color = 2;</code>
       */
      public Builder setColor(mirrorWar.player.Player.PlayerState.Color value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        color_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .mirrorWar.player.PlayerState.Color color = 2;</code>
       */
      public Builder clearColor() {
        bitField0_ = (bitField0_ & ~0x00000002);
        color_ = 1;
        onChanged();
        return this;
      }

      private double x_ ;
      /**
       * <code>required double x = 3;</code>
       */
      public boolean hasX() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required double x = 3;</code>
       */
      public double getX() {
        return x_;
      }
      /**
       * <code>required double x = 3;</code>
       */
      public Builder setX(double value) {
        bitField0_ |= 0x00000004;
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double x = 3;</code>
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000004);
        x_ = 0D;
        onChanged();
        return this;
      }

      private double y_ ;
      /**
       * <code>required double y = 4;</code>
       */
      public boolean hasY() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required double y = 4;</code>
       */
      public double getY() {
        return y_;
      }
      /**
       * <code>required double y = 4;</code>
       */
      public Builder setY(double value) {
        bitField0_ |= 0x00000008;
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double y = 4;</code>
       */
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000008);
        y_ = 0D;
        onChanged();
        return this;
      }

      private int animation_ = 1;
      /**
       * <code>required .mirrorWar.player.PlayerState.Animation animation = 5;</code>
       */
      public boolean hasAnimation() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required .mirrorWar.player.PlayerState.Animation animation = 5;</code>
       */
      public mirrorWar.player.Player.PlayerState.Animation getAnimation() {
        mirrorWar.player.Player.PlayerState.Animation result = mirrorWar.player.Player.PlayerState.Animation.valueOf(animation_);
        return result == null ? mirrorWar.player.Player.PlayerState.Animation.STANDING : result;
      }
      /**
       * <code>required .mirrorWar.player.PlayerState.Animation animation = 5;</code>
       */
      public Builder setAnimation(mirrorWar.player.Player.PlayerState.Animation value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        animation_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .mirrorWar.player.PlayerState.Animation animation = 5;</code>
       */
      public Builder clearAnimation() {
        bitField0_ = (bitField0_ & ~0x00000010);
        animation_ = 1;
        onChanged();
        return this;
      }

      private int facing_ = 1;
      /**
       * <code>required .mirrorWar.player.PlayerState.Facing facing = 6;</code>
       */
      public boolean hasFacing() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required .mirrorWar.player.PlayerState.Facing facing = 6;</code>
       */
      public mirrorWar.player.Player.PlayerState.Facing getFacing() {
        mirrorWar.player.Player.PlayerState.Facing result = mirrorWar.player.Player.PlayerState.Facing.valueOf(facing_);
        return result == null ? mirrorWar.player.Player.PlayerState.Facing.LEFT : result;
      }
      /**
       * <code>required .mirrorWar.player.PlayerState.Facing facing = 6;</code>
       */
      public Builder setFacing(mirrorWar.player.Player.PlayerState.Facing value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000020;
        facing_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .mirrorWar.player.PlayerState.Facing facing = 6;</code>
       */
      public Builder clearFacing() {
        bitField0_ = (bitField0_ & ~0x00000020);
        facing_ = 1;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:mirrorWar.player.PlayerState)
    }

    // @@protoc_insertion_point(class_scope:mirrorWar.player.PlayerState)
    private static final mirrorWar.player.Player.PlayerState DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new mirrorWar.player.Player.PlayerState();
    }

    public static mirrorWar.player.Player.PlayerState getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<PlayerState>
        PARSER = new com.google.protobuf.AbstractParser<PlayerState>() {
      public PlayerState parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PlayerState(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PlayerState> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerState> getParserForType() {
      return PARSER;
    }

    public mirrorWar.player.Player.PlayerState getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mirrorWar_player_PlayerState_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mirrorWar_player_PlayerState_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014player.proto\022\020mirrorWar.player\"\335\002\n\013Pla" +
      "yerState\022\n\n\002id\030\001 \002(\r\0222\n\005color\030\002 \002(\0162#.mi" +
      "rrorWar.player.PlayerState.Color\022\t\n\001x\030\003 " +
      "\002(\001\022\t\n\001y\030\004 \002(\001\022:\n\tanimation\030\005 \002(\0162\'.mirr" +
      "orWar.player.PlayerState.Animation\0224\n\006fa" +
      "cing\030\006 \002(\0162$.mirrorWar.player.PlayerStat" +
      "e.Facing\"?\n\tAnimation\022\014\n\010STANDING\020\001\022\013\n\007W" +
      "ALKING\020\002\022\013\n\007RUNNING\020\003\022\n\n\006KILLED\020\004\"\035\n\006Fac" +
      "ing\022\010\n\004LEFT\020\001\022\t\n\005RIGHT\020\002\"&\n\005Color\022\007\n\003RED" +
      "\020\001\022\010\n\004BLUE\020\002\022\n\n\006ORANGE\020\003"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_mirrorWar_player_PlayerState_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mirrorWar_player_PlayerState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mirrorWar_player_PlayerState_descriptor,
        new java.lang.String[] { "Id", "Color", "X", "Y", "Animation", "Facing", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
