// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: update.proto

package netGameNodeSDK.update;

public final class UpdateOuterClass {
  private UpdateOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UpdateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:netGameNodeSDK.update.Update)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .netGameNodeSDK.player.PlayerState player_state = 1;</code>
     */
    boolean hasPlayerState();
    /**
     * <code>optional .netGameNodeSDK.player.PlayerState player_state = 1;</code>
     */
    mirrorWar.player.Player.PlayerState getPlayerState();
    /**
     * <code>optional .netGameNodeSDK.player.PlayerState player_state = 1;</code>
     */
    mirrorWar.player.Player.PlayerStateOrBuilder getPlayerStateOrBuilder();

    /**
     * <code>optional .netGameNodeSDK.mirror.MirrorState mirror_state = 2;</code>
     */
    boolean hasMirrorState();
    /**
     * <code>optional .netGameNodeSDK.mirror.MirrorState mirror_state = 2;</code>
     */
    mirrorWar.mirror.Mirror.MirrorState getMirrorState();
    /**
     * <code>optional .netGameNodeSDK.mirror.MirrorState mirror_state = 2;</code>
     */
    mirrorWar.mirror.Mirror.MirrorStateOrBuilder getMirrorStateOrBuilder();

    /**
     * <code>optional .netGameNodeSDK.charger.ChargerState charger_state = 3;</code>
     */
    boolean hasChargerState();
    /**
     * <code>optional .netGameNodeSDK.charger.ChargerState charger_state = 3;</code>
     */
    mirrorWar.charger.Charger.ChargerState getChargerState();
    /**
     * <code>optional .netGameNodeSDK.charger.ChargerState charger_state = 3;</code>
     */
    mirrorWar.charger.Charger.ChargerStateOrBuilder getChargerStateOrBuilder();

    public netGameNodeSDK.update.UpdateOuterClass.Update.UpdateCase getUpdateCase();
  }
  /**
   * Protobuf type {@code netGameNodeSDK.update.Update}
   */
  public  static final class Update extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:netGameNodeSDK.update.Update)
      UpdateOrBuilder {
    // Use Update.newBuilder() to construct.
    private Update(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Update() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Update(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              mirrorWar.player.Player.PlayerState.Builder subBuilder = null;
              if (updateCase_ == 1) {
                subBuilder = ((mirrorWar.player.Player.PlayerState) update_).toBuilder();
              }
              update_ =
                  input.readMessage(mirrorWar.player.Player.PlayerState.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((mirrorWar.player.Player.PlayerState) update_);
                update_ = subBuilder.buildPartial();
              }
              updateCase_ = 1;
              break;
            }
            case 18: {
              mirrorWar.mirror.Mirror.MirrorState.Builder subBuilder = null;
              if (updateCase_ == 2) {
                subBuilder = ((mirrorWar.mirror.Mirror.MirrorState) update_).toBuilder();
              }
              update_ =
                  input.readMessage(mirrorWar.mirror.Mirror.MirrorState.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((mirrorWar.mirror.Mirror.MirrorState) update_);
                update_ = subBuilder.buildPartial();
              }
              updateCase_ = 2;
              break;
            }
            case 26: {
              mirrorWar.charger.Charger.ChargerState.Builder subBuilder = null;
              if (updateCase_ == 3) {
                subBuilder = ((mirrorWar.charger.Charger.ChargerState) update_).toBuilder();
              }
              update_ =
                  input.readMessage(mirrorWar.charger.Charger.ChargerState.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((mirrorWar.charger.Charger.ChargerState) update_);
                update_ = subBuilder.buildPartial();
              }
              updateCase_ = 3;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return netGameNodeSDK.update.UpdateOuterClass.internal_static_netGameNodeSDK_update_Update_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return netGameNodeSDK.update.UpdateOuterClass.internal_static_netGameNodeSDK_update_Update_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              netGameNodeSDK.update.UpdateOuterClass.Update.class, netGameNodeSDK.update.UpdateOuterClass.Update.Builder.class);
    }

    private int bitField0_;
    private int updateCase_ = 0;
    private java.lang.Object update_;
    public enum UpdateCase
        implements com.google.protobuf.Internal.EnumLite {
      PLAYER_STATE(1),
      MIRROR_STATE(2),
      CHARGER_STATE(3),
      UPDATE_NOT_SET(0);
      private final int value;
      private UpdateCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static UpdateCase valueOf(int value) {
        return forNumber(value);
      }

      public static UpdateCase forNumber(int value) {
        switch (value) {
          case 1: return PLAYER_STATE;
          case 2: return MIRROR_STATE;
          case 3: return CHARGER_STATE;
          case 0: return UPDATE_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public UpdateCase
    getUpdateCase() {
      return UpdateCase.forNumber(
          updateCase_);
    }

    public static final int PLAYER_STATE_FIELD_NUMBER = 1;
    /**
     * <code>optional .netGameNodeSDK.player.PlayerState player_state = 1;</code>
     */
    public boolean hasPlayerState() {
      return updateCase_ == 1;
    }
    /**
     * <code>optional .netGameNodeSDK.player.PlayerState player_state = 1;</code>
     */
    public mirrorWar.player.Player.PlayerState getPlayerState() {
      if (updateCase_ == 1) {
         return (mirrorWar.player.Player.PlayerState) update_;
      }
      return mirrorWar.player.Player.PlayerState.getDefaultInstance();
    }
    /**
     * <code>optional .netGameNodeSDK.player.PlayerState player_state = 1;</code>
     */
    public mirrorWar.player.Player.PlayerStateOrBuilder getPlayerStateOrBuilder() {
      if (updateCase_ == 1) {
         return (mirrorWar.player.Player.PlayerState) update_;
      }
      return mirrorWar.player.Player.PlayerState.getDefaultInstance();
    }

    public static final int MIRROR_STATE_FIELD_NUMBER = 2;
    /**
     * <code>optional .netGameNodeSDK.mirror.MirrorState mirror_state = 2;</code>
     */
    public boolean hasMirrorState() {
      return updateCase_ == 2;
    }
    /**
     * <code>optional .netGameNodeSDK.mirror.MirrorState mirror_state = 2;</code>
     */
    public mirrorWar.mirror.Mirror.MirrorState getMirrorState() {
      if (updateCase_ == 2) {
         return (mirrorWar.mirror.Mirror.MirrorState) update_;
      }
      return mirrorWar.mirror.Mirror.MirrorState.getDefaultInstance();
    }
    /**
     * <code>optional .netGameNodeSDK.mirror.MirrorState mirror_state = 2;</code>
     */
    public mirrorWar.mirror.Mirror.MirrorStateOrBuilder getMirrorStateOrBuilder() {
      if (updateCase_ == 2) {
         return (mirrorWar.mirror.Mirror.MirrorState) update_;
      }
      return mirrorWar.mirror.Mirror.MirrorState.getDefaultInstance();
    }

    public static final int CHARGER_STATE_FIELD_NUMBER = 3;
    /**
     * <code>optional .netGameNodeSDK.charger.ChargerState charger_state = 3;</code>
     */
    public boolean hasChargerState() {
      return updateCase_ == 3;
    }
    /**
     * <code>optional .netGameNodeSDK.charger.ChargerState charger_state = 3;</code>
     */
    public mirrorWar.charger.Charger.ChargerState getChargerState() {
      if (updateCase_ == 3) {
         return (mirrorWar.charger.Charger.ChargerState) update_;
      }
      return mirrorWar.charger.Charger.ChargerState.getDefaultInstance();
    }
    /**
     * <code>optional .netGameNodeSDK.charger.ChargerState charger_state = 3;</code>
     */
    public mirrorWar.charger.Charger.ChargerStateOrBuilder getChargerStateOrBuilder() {
      if (updateCase_ == 3) {
         return (mirrorWar.charger.Charger.ChargerState) update_;
      }
      return mirrorWar.charger.Charger.ChargerState.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (hasPlayerState()) {
        if (!getPlayerState().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasMirrorState()) {
        if (!getMirrorState().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasChargerState()) {
        if (!getChargerState().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (updateCase_ == 1) {
        output.writeMessage(1, (mirrorWar.player.Player.PlayerState) update_);
      }
      if (updateCase_ == 2) {
        output.writeMessage(2, (mirrorWar.mirror.Mirror.MirrorState) update_);
      }
      if (updateCase_ == 3) {
        output.writeMessage(3, (mirrorWar.charger.Charger.ChargerState) update_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (updateCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (mirrorWar.player.Player.PlayerState) update_);
      }
      if (updateCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (mirrorWar.mirror.Mirror.MirrorState) update_);
      }
      if (updateCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (mirrorWar.charger.Charger.ChargerState) update_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof netGameNodeSDK.update.UpdateOuterClass.Update)) {
        return super.equals(obj);
      }
      netGameNodeSDK.update.UpdateOuterClass.Update other = (netGameNodeSDK.update.UpdateOuterClass.Update) obj;

      boolean result = true;
      result = result && getUpdateCase().equals(
          other.getUpdateCase());
      if (!result) return false;
      switch (updateCase_) {
        case 1:
          result = result && getPlayerState()
              .equals(other.getPlayerState());
          break;
        case 2:
          result = result && getMirrorState()
              .equals(other.getMirrorState());
          break;
        case 3:
          result = result && getChargerState()
              .equals(other.getChargerState());
          break;
        case 0:
        default:
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      switch (updateCase_) {
        case 1:
          hash = (37 * hash) + PLAYER_STATE_FIELD_NUMBER;
          hash = (53 * hash) + getPlayerState().hashCode();
          break;
        case 2:
          hash = (37 * hash) + MIRROR_STATE_FIELD_NUMBER;
          hash = (53 * hash) + getMirrorState().hashCode();
          break;
        case 3:
          hash = (37 * hash) + CHARGER_STATE_FIELD_NUMBER;
          hash = (53 * hash) + getChargerState().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static netGameNodeSDK.update.UpdateOuterClass.Update parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static netGameNodeSDK.update.UpdateOuterClass.Update parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static netGameNodeSDK.update.UpdateOuterClass.Update parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static netGameNodeSDK.update.UpdateOuterClass.Update parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static netGameNodeSDK.update.UpdateOuterClass.Update parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static netGameNodeSDK.update.UpdateOuterClass.Update parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static netGameNodeSDK.update.UpdateOuterClass.Update parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static netGameNodeSDK.update.UpdateOuterClass.Update parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static netGameNodeSDK.update.UpdateOuterClass.Update parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static netGameNodeSDK.update.UpdateOuterClass.Update parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(netGameNodeSDK.update.UpdateOuterClass.Update prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code netGameNodeSDK.update.Update}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:netGameNodeSDK.update.Update)
        netGameNodeSDK.update.UpdateOuterClass.UpdateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return netGameNodeSDK.update.UpdateOuterClass.internal_static_netGameNodeSDK_update_Update_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return netGameNodeSDK.update.UpdateOuterClass.internal_static_netGameNodeSDK_update_Update_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                netGameNodeSDK.update.UpdateOuterClass.Update.class, netGameNodeSDK.update.UpdateOuterClass.Update.Builder.class);
      }

      // Construct using netGameNodeSDK.update.UpdateOuterClass.Update.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        updateCase_ = 0;
        update_ = null;
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return netGameNodeSDK.update.UpdateOuterClass.internal_static_netGameNodeSDK_update_Update_descriptor;
      }

      public netGameNodeSDK.update.UpdateOuterClass.Update getDefaultInstanceForType() {
        return netGameNodeSDK.update.UpdateOuterClass.Update.getDefaultInstance();
      }

      public netGameNodeSDK.update.UpdateOuterClass.Update build() {
        netGameNodeSDK.update.UpdateOuterClass.Update result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public netGameNodeSDK.update.UpdateOuterClass.Update buildPartial() {
        netGameNodeSDK.update.UpdateOuterClass.Update result = new netGameNodeSDK.update.UpdateOuterClass.Update(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (updateCase_ == 1) {
          if (playerStateBuilder_ == null) {
            result.update_ = update_;
          } else {
            result.update_ = playerStateBuilder_.build();
          }
        }
        if (updateCase_ == 2) {
          if (mirrorStateBuilder_ == null) {
            result.update_ = update_;
          } else {
            result.update_ = mirrorStateBuilder_.build();
          }
        }
        if (updateCase_ == 3) {
          if (chargerStateBuilder_ == null) {
            result.update_ = update_;
          } else {
            result.update_ = chargerStateBuilder_.build();
          }
        }
        result.bitField0_ = to_bitField0_;
        result.updateCase_ = updateCase_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof netGameNodeSDK.update.UpdateOuterClass.Update) {
          return mergeFrom((netGameNodeSDK.update.UpdateOuterClass.Update)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(netGameNodeSDK.update.UpdateOuterClass.Update other) {
        if (other == netGameNodeSDK.update.UpdateOuterClass.Update.getDefaultInstance()) return this;
        switch (other.getUpdateCase()) {
          case PLAYER_STATE: {
            mergePlayerState(other.getPlayerState());
            break;
          }
          case MIRROR_STATE: {
            mergeMirrorState(other.getMirrorState());
            break;
          }
          case CHARGER_STATE: {
            mergeChargerState(other.getChargerState());
            break;
          }
          case UPDATE_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (hasPlayerState()) {
          if (!getPlayerState().isInitialized()) {
            return false;
          }
        }
        if (hasMirrorState()) {
          if (!getMirrorState().isInitialized()) {
            return false;
          }
        }
        if (hasChargerState()) {
          if (!getChargerState().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        netGameNodeSDK.update.UpdateOuterClass.Update parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (netGameNodeSDK.update.UpdateOuterClass.Update) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int updateCase_ = 0;
      private java.lang.Object update_;
      public UpdateCase
          getUpdateCase() {
        return UpdateCase.forNumber(
            updateCase_);
      }

      public Builder clearUpdate() {
        updateCase_ = 0;
        update_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private com.google.protobuf.SingleFieldBuilderV3<
          mirrorWar.player.Player.PlayerState, mirrorWar.player.Player.PlayerState.Builder, mirrorWar.player.Player.PlayerStateOrBuilder> playerStateBuilder_;
      /**
       * <code>optional .netGameNodeSDK.player.PlayerState player_state = 1;</code>
       */
      public boolean hasPlayerState() {
        return updateCase_ == 1;
      }
      /**
       * <code>optional .netGameNodeSDK.player.PlayerState player_state = 1;</code>
       */
      public mirrorWar.player.Player.PlayerState getPlayerState() {
        if (playerStateBuilder_ == null) {
          if (updateCase_ == 1) {
            return (mirrorWar.player.Player.PlayerState) update_;
          }
          return mirrorWar.player.Player.PlayerState.getDefaultInstance();
        } else {
          if (updateCase_ == 1) {
            return playerStateBuilder_.getMessage();
          }
          return mirrorWar.player.Player.PlayerState.getDefaultInstance();
        }
      }
      /**
       * <code>optional .netGameNodeSDK.player.PlayerState player_state = 1;</code>
       */
      public Builder setPlayerState(mirrorWar.player.Player.PlayerState value) {
        if (playerStateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          update_ = value;
          onChanged();
        } else {
          playerStateBuilder_.setMessage(value);
        }
        updateCase_ = 1;
        return this;
      }
      /**
       * <code>optional .netGameNodeSDK.player.PlayerState player_state = 1;</code>
       */
      public Builder setPlayerState(
          mirrorWar.player.Player.PlayerState.Builder builderForValue) {
        if (playerStateBuilder_ == null) {
          update_ = builderForValue.build();
          onChanged();
        } else {
          playerStateBuilder_.setMessage(builderForValue.build());
        }
        updateCase_ = 1;
        return this;
      }
      /**
       * <code>optional .netGameNodeSDK.player.PlayerState player_state = 1;</code>
       */
      public Builder mergePlayerState(mirrorWar.player.Player.PlayerState value) {
        if (playerStateBuilder_ == null) {
          if (updateCase_ == 1 &&
              update_ != mirrorWar.player.Player.PlayerState.getDefaultInstance()) {
            update_ = mirrorWar.player.Player.PlayerState.newBuilder((mirrorWar.player.Player.PlayerState) update_)
                .mergeFrom(value).buildPartial();
          } else {
            update_ = value;
          }
          onChanged();
        } else {
          if (updateCase_ == 1) {
            playerStateBuilder_.mergeFrom(value);
          }
          playerStateBuilder_.setMessage(value);
        }
        updateCase_ = 1;
        return this;
      }
      /**
       * <code>optional .netGameNodeSDK.player.PlayerState player_state = 1;</code>
       */
      public Builder clearPlayerState() {
        if (playerStateBuilder_ == null) {
          if (updateCase_ == 1) {
            updateCase_ = 0;
            update_ = null;
            onChanged();
          }
        } else {
          if (updateCase_ == 1) {
            updateCase_ = 0;
            update_ = null;
          }
          playerStateBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .netGameNodeSDK.player.PlayerState player_state = 1;</code>
       */
      public mirrorWar.player.Player.PlayerState.Builder getPlayerStateBuilder() {
        return getPlayerStateFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .netGameNodeSDK.player.PlayerState player_state = 1;</code>
       */
      public mirrorWar.player.Player.PlayerStateOrBuilder getPlayerStateOrBuilder() {
        if ((updateCase_ == 1) && (playerStateBuilder_ != null)) {
          return playerStateBuilder_.getMessageOrBuilder();
        } else {
          if (updateCase_ == 1) {
            return (mirrorWar.player.Player.PlayerState) update_;
          }
          return mirrorWar.player.Player.PlayerState.getDefaultInstance();
        }
      }
      /**
       * <code>optional .netGameNodeSDK.player.PlayerState player_state = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          mirrorWar.player.Player.PlayerState, mirrorWar.player.Player.PlayerState.Builder, mirrorWar.player.Player.PlayerStateOrBuilder> 
          getPlayerStateFieldBuilder() {
        if (playerStateBuilder_ == null) {
          if (!(updateCase_ == 1)) {
            update_ = mirrorWar.player.Player.PlayerState.getDefaultInstance();
          }
          playerStateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              mirrorWar.player.Player.PlayerState, mirrorWar.player.Player.PlayerState.Builder, mirrorWar.player.Player.PlayerStateOrBuilder>(
                  (mirrorWar.player.Player.PlayerState) update_,
                  getParentForChildren(),
                  isClean());
          update_ = null;
        }
        updateCase_ = 1;
        onChanged();;
        return playerStateBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          mirrorWar.mirror.Mirror.MirrorState, mirrorWar.mirror.Mirror.MirrorState.Builder, mirrorWar.mirror.Mirror.MirrorStateOrBuilder> mirrorStateBuilder_;
      /**
       * <code>optional .netGameNodeSDK.mirror.MirrorState mirror_state = 2;</code>
       */
      public boolean hasMirrorState() {
        return updateCase_ == 2;
      }
      /**
       * <code>optional .netGameNodeSDK.mirror.MirrorState mirror_state = 2;</code>
       */
      public mirrorWar.mirror.Mirror.MirrorState getMirrorState() {
        if (mirrorStateBuilder_ == null) {
          if (updateCase_ == 2) {
            return (mirrorWar.mirror.Mirror.MirrorState) update_;
          }
          return mirrorWar.mirror.Mirror.MirrorState.getDefaultInstance();
        } else {
          if (updateCase_ == 2) {
            return mirrorStateBuilder_.getMessage();
          }
          return mirrorWar.mirror.Mirror.MirrorState.getDefaultInstance();
        }
      }
      /**
       * <code>optional .netGameNodeSDK.mirror.MirrorState mirror_state = 2;</code>
       */
      public Builder setMirrorState(mirrorWar.mirror.Mirror.MirrorState value) {
        if (mirrorStateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          update_ = value;
          onChanged();
        } else {
          mirrorStateBuilder_.setMessage(value);
        }
        updateCase_ = 2;
        return this;
      }
      /**
       * <code>optional .netGameNodeSDK.mirror.MirrorState mirror_state = 2;</code>
       */
      public Builder setMirrorState(
          mirrorWar.mirror.Mirror.MirrorState.Builder builderForValue) {
        if (mirrorStateBuilder_ == null) {
          update_ = builderForValue.build();
          onChanged();
        } else {
          mirrorStateBuilder_.setMessage(builderForValue.build());
        }
        updateCase_ = 2;
        return this;
      }
      /**
       * <code>optional .netGameNodeSDK.mirror.MirrorState mirror_state = 2;</code>
       */
      public Builder mergeMirrorState(mirrorWar.mirror.Mirror.MirrorState value) {
        if (mirrorStateBuilder_ == null) {
          if (updateCase_ == 2 &&
              update_ != mirrorWar.mirror.Mirror.MirrorState.getDefaultInstance()) {
            update_ = mirrorWar.mirror.Mirror.MirrorState.newBuilder((mirrorWar.mirror.Mirror.MirrorState) update_)
                .mergeFrom(value).buildPartial();
          } else {
            update_ = value;
          }
          onChanged();
        } else {
          if (updateCase_ == 2) {
            mirrorStateBuilder_.mergeFrom(value);
          }
          mirrorStateBuilder_.setMessage(value);
        }
        updateCase_ = 2;
        return this;
      }
      /**
       * <code>optional .netGameNodeSDK.mirror.MirrorState mirror_state = 2;</code>
       */
      public Builder clearMirrorState() {
        if (mirrorStateBuilder_ == null) {
          if (updateCase_ == 2) {
            updateCase_ = 0;
            update_ = null;
            onChanged();
          }
        } else {
          if (updateCase_ == 2) {
            updateCase_ = 0;
            update_ = null;
          }
          mirrorStateBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .netGameNodeSDK.mirror.MirrorState mirror_state = 2;</code>
       */
      public mirrorWar.mirror.Mirror.MirrorState.Builder getMirrorStateBuilder() {
        return getMirrorStateFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .netGameNodeSDK.mirror.MirrorState mirror_state = 2;</code>
       */
      public mirrorWar.mirror.Mirror.MirrorStateOrBuilder getMirrorStateOrBuilder() {
        if ((updateCase_ == 2) && (mirrorStateBuilder_ != null)) {
          return mirrorStateBuilder_.getMessageOrBuilder();
        } else {
          if (updateCase_ == 2) {
            return (mirrorWar.mirror.Mirror.MirrorState) update_;
          }
          return mirrorWar.mirror.Mirror.MirrorState.getDefaultInstance();
        }
      }
      /**
       * <code>optional .netGameNodeSDK.mirror.MirrorState mirror_state = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          mirrorWar.mirror.Mirror.MirrorState, mirrorWar.mirror.Mirror.MirrorState.Builder, mirrorWar.mirror.Mirror.MirrorStateOrBuilder> 
          getMirrorStateFieldBuilder() {
        if (mirrorStateBuilder_ == null) {
          if (!(updateCase_ == 2)) {
            update_ = mirrorWar.mirror.Mirror.MirrorState.getDefaultInstance();
          }
          mirrorStateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              mirrorWar.mirror.Mirror.MirrorState, mirrorWar.mirror.Mirror.MirrorState.Builder, mirrorWar.mirror.Mirror.MirrorStateOrBuilder>(
                  (mirrorWar.mirror.Mirror.MirrorState) update_,
                  getParentForChildren(),
                  isClean());
          update_ = null;
        }
        updateCase_ = 2;
        onChanged();;
        return mirrorStateBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          mirrorWar.charger.Charger.ChargerState, mirrorWar.charger.Charger.ChargerState.Builder, mirrorWar.charger.Charger.ChargerStateOrBuilder> chargerStateBuilder_;
      /**
       * <code>optional .netGameNodeSDK.charger.ChargerState charger_state = 3;</code>
       */
      public boolean hasChargerState() {
        return updateCase_ == 3;
      }
      /**
       * <code>optional .netGameNodeSDK.charger.ChargerState charger_state = 3;</code>
       */
      public mirrorWar.charger.Charger.ChargerState getChargerState() {
        if (chargerStateBuilder_ == null) {
          if (updateCase_ == 3) {
            return (mirrorWar.charger.Charger.ChargerState) update_;
          }
          return mirrorWar.charger.Charger.ChargerState.getDefaultInstance();
        } else {
          if (updateCase_ == 3) {
            return chargerStateBuilder_.getMessage();
          }
          return mirrorWar.charger.Charger.ChargerState.getDefaultInstance();
        }
      }
      /**
       * <code>optional .netGameNodeSDK.charger.ChargerState charger_state = 3;</code>
       */
      public Builder setChargerState(mirrorWar.charger.Charger.ChargerState value) {
        if (chargerStateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          update_ = value;
          onChanged();
        } else {
          chargerStateBuilder_.setMessage(value);
        }
        updateCase_ = 3;
        return this;
      }
      /**
       * <code>optional .netGameNodeSDK.charger.ChargerState charger_state = 3;</code>
       */
      public Builder setChargerState(
          mirrorWar.charger.Charger.ChargerState.Builder builderForValue) {
        if (chargerStateBuilder_ == null) {
          update_ = builderForValue.build();
          onChanged();
        } else {
          chargerStateBuilder_.setMessage(builderForValue.build());
        }
        updateCase_ = 3;
        return this;
      }
      /**
       * <code>optional .netGameNodeSDK.charger.ChargerState charger_state = 3;</code>
       */
      public Builder mergeChargerState(mirrorWar.charger.Charger.ChargerState value) {
        if (chargerStateBuilder_ == null) {
          if (updateCase_ == 3 &&
              update_ != mirrorWar.charger.Charger.ChargerState.getDefaultInstance()) {
            update_ = mirrorWar.charger.Charger.ChargerState.newBuilder((mirrorWar.charger.Charger.ChargerState) update_)
                .mergeFrom(value).buildPartial();
          } else {
            update_ = value;
          }
          onChanged();
        } else {
          if (updateCase_ == 3) {
            chargerStateBuilder_.mergeFrom(value);
          }
          chargerStateBuilder_.setMessage(value);
        }
        updateCase_ = 3;
        return this;
      }
      /**
       * <code>optional .netGameNodeSDK.charger.ChargerState charger_state = 3;</code>
       */
      public Builder clearChargerState() {
        if (chargerStateBuilder_ == null) {
          if (updateCase_ == 3) {
            updateCase_ = 0;
            update_ = null;
            onChanged();
          }
        } else {
          if (updateCase_ == 3) {
            updateCase_ = 0;
            update_ = null;
          }
          chargerStateBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .netGameNodeSDK.charger.ChargerState charger_state = 3;</code>
       */
      public mirrorWar.charger.Charger.ChargerState.Builder getChargerStateBuilder() {
        return getChargerStateFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .netGameNodeSDK.charger.ChargerState charger_state = 3;</code>
       */
      public mirrorWar.charger.Charger.ChargerStateOrBuilder getChargerStateOrBuilder() {
        if ((updateCase_ == 3) && (chargerStateBuilder_ != null)) {
          return chargerStateBuilder_.getMessageOrBuilder();
        } else {
          if (updateCase_ == 3) {
            return (mirrorWar.charger.Charger.ChargerState) update_;
          }
          return mirrorWar.charger.Charger.ChargerState.getDefaultInstance();
        }
      }
      /**
       * <code>optional .netGameNodeSDK.charger.ChargerState charger_state = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          mirrorWar.charger.Charger.ChargerState, mirrorWar.charger.Charger.ChargerState.Builder, mirrorWar.charger.Charger.ChargerStateOrBuilder> 
          getChargerStateFieldBuilder() {
        if (chargerStateBuilder_ == null) {
          if (!(updateCase_ == 3)) {
            update_ = mirrorWar.charger.Charger.ChargerState.getDefaultInstance();
          }
          chargerStateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              mirrorWar.charger.Charger.ChargerState, mirrorWar.charger.Charger.ChargerState.Builder, mirrorWar.charger.Charger.ChargerStateOrBuilder>(
                  (mirrorWar.charger.Charger.ChargerState) update_,
                  getParentForChildren(),
                  isClean());
          update_ = null;
        }
        updateCase_ = 3;
        onChanged();;
        return chargerStateBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:netGameNodeSDK.update.Update)
    }

    // @@protoc_insertion_point(class_scope:netGameNodeSDK.update.Update)
    private static final netGameNodeSDK.update.UpdateOuterClass.Update DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new netGameNodeSDK.update.UpdateOuterClass.Update();
    }

    public static netGameNodeSDK.update.UpdateOuterClass.Update getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Update>
        PARSER = new com.google.protobuf.AbstractParser<Update>() {
      public Update parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Update(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Update> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Update> getParserForType() {
      return PARSER;
    }

    public netGameNodeSDK.update.UpdateOuterClass.Update getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UpdatesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:netGameNodeSDK.update.Updates)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .netGameNodeSDK.update.Update updates = 1;</code>
     */
    java.util.List<netGameNodeSDK.update.UpdateOuterClass.Update> 
        getUpdatesList();
    /**
     * <code>repeated .netGameNodeSDK.update.Update updates = 1;</code>
     */
    netGameNodeSDK.update.UpdateOuterClass.Update getUpdates(int index);
    /**
     * <code>repeated .netGameNodeSDK.update.Update updates = 1;</code>
     */
    int getUpdatesCount();
    /**
     * <code>repeated .netGameNodeSDK.update.Update updates = 1;</code>
     */
    java.util.List<? extends netGameNodeSDK.update.UpdateOuterClass.UpdateOrBuilder> 
        getUpdatesOrBuilderList();
    /**
     * <code>repeated .netGameNodeSDK.update.Update updates = 1;</code>
     */
    netGameNodeSDK.update.UpdateOuterClass.UpdateOrBuilder getUpdatesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code netGameNodeSDK.update.Updates}
   */
  public  static final class Updates extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:netGameNodeSDK.update.Updates)
      UpdatesOrBuilder {
    // Use Updates.newBuilder() to construct.
    private Updates(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Updates() {
      updates_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Updates(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                updates_ = new java.util.ArrayList<netGameNodeSDK.update.UpdateOuterClass.Update>();
                mutable_bitField0_ |= 0x00000001;
              }
              updates_.add(
                  input.readMessage(netGameNodeSDK.update.UpdateOuterClass.Update.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          updates_ = java.util.Collections.unmodifiableList(updates_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return netGameNodeSDK.update.UpdateOuterClass.internal_static_netGameNodeSDK_update_Updates_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return netGameNodeSDK.update.UpdateOuterClass.internal_static_netGameNodeSDK_update_Updates_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              netGameNodeSDK.update.UpdateOuterClass.Updates.class, netGameNodeSDK.update.UpdateOuterClass.Updates.Builder.class);
    }

    public static final int UPDATES_FIELD_NUMBER = 1;
    private java.util.List<netGameNodeSDK.update.UpdateOuterClass.Update> updates_;
    /**
     * <code>repeated .netGameNodeSDK.update.Update updates = 1;</code>
     */
    public java.util.List<netGameNodeSDK.update.UpdateOuterClass.Update> getUpdatesList() {
      return updates_;
    }
    /**
     * <code>repeated .netGameNodeSDK.update.Update updates = 1;</code>
     */
    public java.util.List<? extends netGameNodeSDK.update.UpdateOuterClass.UpdateOrBuilder> 
        getUpdatesOrBuilderList() {
      return updates_;
    }
    /**
     * <code>repeated .netGameNodeSDK.update.Update updates = 1;</code>
     */
    public int getUpdatesCount() {
      return updates_.size();
    }
    /**
     * <code>repeated .netGameNodeSDK.update.Update updates = 1;</code>
     */
    public netGameNodeSDK.update.UpdateOuterClass.Update getUpdates(int index) {
      return updates_.get(index);
    }
    /**
     * <code>repeated .netGameNodeSDK.update.Update updates = 1;</code>
     */
    public netGameNodeSDK.update.UpdateOuterClass.UpdateOrBuilder getUpdatesOrBuilder(
        int index) {
      return updates_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getUpdatesCount(); i++) {
        if (!getUpdates(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < updates_.size(); i++) {
        output.writeMessage(1, updates_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < updates_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, updates_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof netGameNodeSDK.update.UpdateOuterClass.Updates)) {
        return super.equals(obj);
      }
      netGameNodeSDK.update.UpdateOuterClass.Updates other = (netGameNodeSDK.update.UpdateOuterClass.Updates) obj;

      boolean result = true;
      result = result && getUpdatesList()
          .equals(other.getUpdatesList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getUpdatesCount() > 0) {
        hash = (37 * hash) + UPDATES_FIELD_NUMBER;
        hash = (53 * hash) + getUpdatesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static netGameNodeSDK.update.UpdateOuterClass.Updates parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static netGameNodeSDK.update.UpdateOuterClass.Updates parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static netGameNodeSDK.update.UpdateOuterClass.Updates parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static netGameNodeSDK.update.UpdateOuterClass.Updates parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static netGameNodeSDK.update.UpdateOuterClass.Updates parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static netGameNodeSDK.update.UpdateOuterClass.Updates parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static netGameNodeSDK.update.UpdateOuterClass.Updates parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static netGameNodeSDK.update.UpdateOuterClass.Updates parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static netGameNodeSDK.update.UpdateOuterClass.Updates parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static netGameNodeSDK.update.UpdateOuterClass.Updates parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(netGameNodeSDK.update.UpdateOuterClass.Updates prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code netGameNodeSDK.update.Updates}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:netGameNodeSDK.update.Updates)
        netGameNodeSDK.update.UpdateOuterClass.UpdatesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return netGameNodeSDK.update.UpdateOuterClass.internal_static_netGameNodeSDK_update_Updates_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return netGameNodeSDK.update.UpdateOuterClass.internal_static_netGameNodeSDK_update_Updates_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                netGameNodeSDK.update.UpdateOuterClass.Updates.class, netGameNodeSDK.update.UpdateOuterClass.Updates.Builder.class);
      }

      // Construct using netGameNodeSDK.update.UpdateOuterClass.Updates.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getUpdatesFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (updatesBuilder_ == null) {
          updates_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          updatesBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return netGameNodeSDK.update.UpdateOuterClass.internal_static_netGameNodeSDK_update_Updates_descriptor;
      }

      public netGameNodeSDK.update.UpdateOuterClass.Updates getDefaultInstanceForType() {
        return netGameNodeSDK.update.UpdateOuterClass.Updates.getDefaultInstance();
      }

      public netGameNodeSDK.update.UpdateOuterClass.Updates build() {
        netGameNodeSDK.update.UpdateOuterClass.Updates result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public netGameNodeSDK.update.UpdateOuterClass.Updates buildPartial() {
        netGameNodeSDK.update.UpdateOuterClass.Updates result = new netGameNodeSDK.update.UpdateOuterClass.Updates(this);
        int from_bitField0_ = bitField0_;
        if (updatesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            updates_ = java.util.Collections.unmodifiableList(updates_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.updates_ = updates_;
        } else {
          result.updates_ = updatesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof netGameNodeSDK.update.UpdateOuterClass.Updates) {
          return mergeFrom((netGameNodeSDK.update.UpdateOuterClass.Updates)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(netGameNodeSDK.update.UpdateOuterClass.Updates other) {
        if (other == netGameNodeSDK.update.UpdateOuterClass.Updates.getDefaultInstance()) return this;
        if (updatesBuilder_ == null) {
          if (!other.updates_.isEmpty()) {
            if (updates_.isEmpty()) {
              updates_ = other.updates_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureUpdatesIsMutable();
              updates_.addAll(other.updates_);
            }
            onChanged();
          }
        } else {
          if (!other.updates_.isEmpty()) {
            if (updatesBuilder_.isEmpty()) {
              updatesBuilder_.dispose();
              updatesBuilder_ = null;
              updates_ = other.updates_;
              bitField0_ = (bitField0_ & ~0x00000001);
              updatesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getUpdatesFieldBuilder() : null;
            } else {
              updatesBuilder_.addAllMessages(other.updates_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getUpdatesCount(); i++) {
          if (!getUpdates(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        netGameNodeSDK.update.UpdateOuterClass.Updates parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (netGameNodeSDK.update.UpdateOuterClass.Updates) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<netGameNodeSDK.update.UpdateOuterClass.Update> updates_ =
        java.util.Collections.emptyList();
      private void ensureUpdatesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          updates_ = new java.util.ArrayList<netGameNodeSDK.update.UpdateOuterClass.Update>(updates_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          netGameNodeSDK.update.UpdateOuterClass.Update, netGameNodeSDK.update.UpdateOuterClass.Update.Builder, netGameNodeSDK.update.UpdateOuterClass.UpdateOrBuilder> updatesBuilder_;

      /**
       * <code>repeated .netGameNodeSDK.update.Update updates = 1;</code>
       */
      public java.util.List<netGameNodeSDK.update.UpdateOuterClass.Update> getUpdatesList() {
        if (updatesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(updates_);
        } else {
          return updatesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .netGameNodeSDK.update.Update updates = 1;</code>
       */
      public int getUpdatesCount() {
        if (updatesBuilder_ == null) {
          return updates_.size();
        } else {
          return updatesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .netGameNodeSDK.update.Update updates = 1;</code>
       */
      public netGameNodeSDK.update.UpdateOuterClass.Update getUpdates(int index) {
        if (updatesBuilder_ == null) {
          return updates_.get(index);
        } else {
          return updatesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .netGameNodeSDK.update.Update updates = 1;</code>
       */
      public Builder setUpdates(
          int index, netGameNodeSDK.update.UpdateOuterClass.Update value) {
        if (updatesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUpdatesIsMutable();
          updates_.set(index, value);
          onChanged();
        } else {
          updatesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .netGameNodeSDK.update.Update updates = 1;</code>
       */
      public Builder setUpdates(
          int index, netGameNodeSDK.update.UpdateOuterClass.Update.Builder builderForValue) {
        if (updatesBuilder_ == null) {
          ensureUpdatesIsMutable();
          updates_.set(index, builderForValue.build());
          onChanged();
        } else {
          updatesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .netGameNodeSDK.update.Update updates = 1;</code>
       */
      public Builder addUpdates(netGameNodeSDK.update.UpdateOuterClass.Update value) {
        if (updatesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUpdatesIsMutable();
          updates_.add(value);
          onChanged();
        } else {
          updatesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .netGameNodeSDK.update.Update updates = 1;</code>
       */
      public Builder addUpdates(
          int index, netGameNodeSDK.update.UpdateOuterClass.Update value) {
        if (updatesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUpdatesIsMutable();
          updates_.add(index, value);
          onChanged();
        } else {
          updatesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .netGameNodeSDK.update.Update updates = 1;</code>
       */
      public Builder addUpdates(
          netGameNodeSDK.update.UpdateOuterClass.Update.Builder builderForValue) {
        if (updatesBuilder_ == null) {
          ensureUpdatesIsMutable();
          updates_.add(builderForValue.build());
          onChanged();
        } else {
          updatesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .netGameNodeSDK.update.Update updates = 1;</code>
       */
      public Builder addUpdates(
          int index, netGameNodeSDK.update.UpdateOuterClass.Update.Builder builderForValue) {
        if (updatesBuilder_ == null) {
          ensureUpdatesIsMutable();
          updates_.add(index, builderForValue.build());
          onChanged();
        } else {
          updatesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .netGameNodeSDK.update.Update updates = 1;</code>
       */
      public Builder addAllUpdates(
          java.lang.Iterable<? extends netGameNodeSDK.update.UpdateOuterClass.Update> values) {
        if (updatesBuilder_ == null) {
          ensureUpdatesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, updates_);
          onChanged();
        } else {
          updatesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .netGameNodeSDK.update.Update updates = 1;</code>
       */
      public Builder clearUpdates() {
        if (updatesBuilder_ == null) {
          updates_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          updatesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .netGameNodeSDK.update.Update updates = 1;</code>
       */
      public Builder removeUpdates(int index) {
        if (updatesBuilder_ == null) {
          ensureUpdatesIsMutable();
          updates_.remove(index);
          onChanged();
        } else {
          updatesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .netGameNodeSDK.update.Update updates = 1;</code>
       */
      public netGameNodeSDK.update.UpdateOuterClass.Update.Builder getUpdatesBuilder(
          int index) {
        return getUpdatesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .netGameNodeSDK.update.Update updates = 1;</code>
       */
      public netGameNodeSDK.update.UpdateOuterClass.UpdateOrBuilder getUpdatesOrBuilder(
          int index) {
        if (updatesBuilder_ == null) {
          return updates_.get(index);  } else {
          return updatesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .netGameNodeSDK.update.Update updates = 1;</code>
       */
      public java.util.List<? extends netGameNodeSDK.update.UpdateOuterClass.UpdateOrBuilder> 
           getUpdatesOrBuilderList() {
        if (updatesBuilder_ != null) {
          return updatesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(updates_);
        }
      }
      /**
       * <code>repeated .netGameNodeSDK.update.Update updates = 1;</code>
       */
      public netGameNodeSDK.update.UpdateOuterClass.Update.Builder addUpdatesBuilder() {
        return getUpdatesFieldBuilder().addBuilder(
            netGameNodeSDK.update.UpdateOuterClass.Update.getDefaultInstance());
      }
      /**
       * <code>repeated .netGameNodeSDK.update.Update updates = 1;</code>
       */
      public netGameNodeSDK.update.UpdateOuterClass.Update.Builder addUpdatesBuilder(
          int index) {
        return getUpdatesFieldBuilder().addBuilder(
            index, netGameNodeSDK.update.UpdateOuterClass.Update.getDefaultInstance());
      }
      /**
       * <code>repeated .netGameNodeSDK.update.Update updates = 1;</code>
       */
      public java.util.List<netGameNodeSDK.update.UpdateOuterClass.Update.Builder> 
           getUpdatesBuilderList() {
        return getUpdatesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          netGameNodeSDK.update.UpdateOuterClass.Update, netGameNodeSDK.update.UpdateOuterClass.Update.Builder, netGameNodeSDK.update.UpdateOuterClass.UpdateOrBuilder> 
          getUpdatesFieldBuilder() {
        if (updatesBuilder_ == null) {
          updatesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              netGameNodeSDK.update.UpdateOuterClass.Update, netGameNodeSDK.update.UpdateOuterClass.Update.Builder, netGameNodeSDK.update.UpdateOuterClass.UpdateOrBuilder>(
                  updates_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          updates_ = null;
        }
        return updatesBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:netGameNodeSDK.update.Updates)
    }

    // @@protoc_insertion_point(class_scope:netGameNodeSDK.update.Updates)
    private static final netGameNodeSDK.update.UpdateOuterClass.Updates DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new netGameNodeSDK.update.UpdateOuterClass.Updates();
    }

    public static netGameNodeSDK.update.UpdateOuterClass.Updates getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Updates>
        PARSER = new com.google.protobuf.AbstractParser<Updates>() {
      public Updates parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Updates(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Updates> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Updates> getParserForType() {
      return PARSER;
    }

    public netGameNodeSDK.update.UpdateOuterClass.Updates getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_netGameNodeSDK_update_Update_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_netGameNodeSDK_update_Update_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_netGameNodeSDK_update_Updates_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_netGameNodeSDK_update_Updates_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014update.proto\022\025netGameNodeSDK.update\032\014p" +
      "layer.proto\032\014mirror.proto\032\rcharger.proto" +
      "\"\311\001\n\006Update\022:\n\014player_state\030\001 \001(\0132\".netG" +
      "ameNodeSDK.player.PlayerStateH\000\022:\n\014mirro" +
      "r_state\030\002 \001(\0132\".netGameNodeSDK.mirror.Mi" +
      "rrorStateH\000\022=\n\rcharger_state\030\003 \001(\0132$.net" +
      "GameNodeSDK.charger.ChargerStateH\000B\010\n\006up" +
      "date\"9\n\007Updates\022.\n\007updates\030\001 \003(\0132\035.netGa" +
      "meNodeSDK.update.Update"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          mirrorWar.player.Player.getDescriptor(),
          mirrorWar.mirror.Mirror.getDescriptor(),
          mirrorWar.charger.Charger.getDescriptor(),
        }, assigner);
    internal_static_netGameNodeSDK_update_Update_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_netGameNodeSDK_update_Update_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_netGameNodeSDK_update_Update_descriptor,
        new java.lang.String[] { "PlayerState", "MirrorState", "ChargerState", "Update", });
    internal_static_netGameNodeSDK_update_Updates_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_netGameNodeSDK_update_Updates_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_netGameNodeSDK_update_Updates_descriptor,
        new java.lang.String[] { "Updates", });
    mirrorWar.player.Player.getDescriptor();
    mirrorWar.mirror.Mirror.getDescriptor();
    mirrorWar.charger.Charger.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
