// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mirror.proto

package netGameNodeSDK.mirror;

public final class Mirror {
  private Mirror() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MirrorStateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:netGameNodeSDK.mirror.MirrorState)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required uint32 id = 1;</code>
     */
    int getId();

    /**
     * <code>required double x = 2;</code>
     */
    boolean hasX();
    /**
     * <code>required double x = 2;</code>
     */
    double getX();

    /**
     * <code>required double y = 3;</code>
     */
    boolean hasY();
    /**
     * <code>required double y = 3;</code>
     */
    double getY();

    /**
     * <code>required bool picked = 4;</code>
     */
    boolean hasPicked();
    /**
     * <code>required bool picked = 4;</code>
     */
    boolean getPicked();

    /**
     * <code>required .netGameNodeSDK.mirror.MirrorState.Direction direction = 5;</code>
     */
    boolean hasDirection();
    /**
     * <code>required .netGameNodeSDK.mirror.MirrorState.Direction direction = 5;</code>
     */
    netGameNodeSDK.mirror.Mirror.MirrorState.Direction getDirection();
  }
  /**
   * Protobuf type {@code netGameNodeSDK.mirror.MirrorState}
   */
  public  static final class MirrorState extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:netGameNodeSDK.mirror.MirrorState)
      MirrorStateOrBuilder {
    // Use MirrorState.newBuilder() to construct.
    private MirrorState(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MirrorState() {
      id_ = 0;
      x_ = 0D;
      y_ = 0D;
      picked_ = false;
      direction_ = 1;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MirrorState(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readUInt32();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              x_ = input.readDouble();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              y_ = input.readDouble();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              picked_ = input.readBool();
              break;
            }
            case 40: {
              int rawValue = input.readEnum();
              netGameNodeSDK.mirror.Mirror.MirrorState.Direction value = netGameNodeSDK.mirror.Mirror.MirrorState.Direction.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(5, rawValue);
              } else {
                bitField0_ |= 0x00000010;
                direction_ = rawValue;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return netGameNodeSDK.mirror.Mirror.internal_static_netGameNodeSDK_mirror_MirrorState_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return netGameNodeSDK.mirror.Mirror.internal_static_netGameNodeSDK_mirror_MirrorState_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              netGameNodeSDK.mirror.Mirror.MirrorState.class, netGameNodeSDK.mirror.Mirror.MirrorState.Builder.class);
    }

    /**
     * Protobuf enum {@code netGameNodeSDK.mirror.MirrorState.Direction}
     */
    public enum Direction
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>SLASH = 1;</code>
       */
      SLASH(1),
      /**
       * <code>BACK_SLACK = 2;</code>
       */
      BACK_SLACK(2),
      ;

      /**
       * <code>SLASH = 1;</code>
       */
      public static final int SLASH_VALUE = 1;
      /**
       * <code>BACK_SLACK = 2;</code>
       */
      public static final int BACK_SLACK_VALUE = 2;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Direction valueOf(int value) {
        return forNumber(value);
      }

      public static Direction forNumber(int value) {
        switch (value) {
          case 1: return SLASH;
          case 2: return BACK_SLACK;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Direction>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Direction> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Direction>() {
              public Direction findValueByNumber(int number) {
                return Direction.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return netGameNodeSDK.mirror.Mirror.MirrorState.getDescriptor().getEnumTypes().get(0);
      }

      private static final Direction[] VALUES = values();

      public static Direction valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Direction(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:netGameNodeSDK.mirror.MirrorState.Direction)
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required uint32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int X_FIELD_NUMBER = 2;
    private double x_;
    /**
     * <code>required double x = 2;</code>
     */
    public boolean hasX() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required double x = 2;</code>
     */
    public double getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 3;
    private double y_;
    /**
     * <code>required double y = 3;</code>
     */
    public boolean hasY() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required double y = 3;</code>
     */
    public double getY() {
      return y_;
    }

    public static final int PICKED_FIELD_NUMBER = 4;
    private boolean picked_;
    /**
     * <code>required bool picked = 4;</code>
     */
    public boolean hasPicked() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required bool picked = 4;</code>
     */
    public boolean getPicked() {
      return picked_;
    }

    public static final int DIRECTION_FIELD_NUMBER = 5;
    private int direction_;
    /**
     * <code>required .netGameNodeSDK.mirror.MirrorState.Direction direction = 5;</code>
     */
    public boolean hasDirection() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required .netGameNodeSDK.mirror.MirrorState.Direction direction = 5;</code>
     */
    public netGameNodeSDK.mirror.Mirror.MirrorState.Direction getDirection() {
      netGameNodeSDK.mirror.Mirror.MirrorState.Direction result = netGameNodeSDK.mirror.Mirror.MirrorState.Direction.valueOf(direction_);
      return result == null ? netGameNodeSDK.mirror.Mirror.MirrorState.Direction.SLASH : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasX()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasY()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPicked()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDirection()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, x_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, y_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(4, picked_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeEnum(5, direction_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, x_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, y_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, picked_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, direction_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof netGameNodeSDK.mirror.Mirror.MirrorState)) {
        return super.equals(obj);
      }
      netGameNodeSDK.mirror.Mirror.MirrorState other = (netGameNodeSDK.mirror.Mirror.MirrorState) obj;

      boolean result = true;
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && (getId()
            == other.getId());
      }
      result = result && (hasX() == other.hasX());
      if (hasX()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getX())
            == java.lang.Double.doubleToLongBits(
                other.getX()));
      }
      result = result && (hasY() == other.hasY());
      if (hasY()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getY())
            == java.lang.Double.doubleToLongBits(
                other.getY()));
      }
      result = result && (hasPicked() == other.hasPicked());
      if (hasPicked()) {
        result = result && (getPicked()
            == other.getPicked());
      }
      result = result && (hasDirection() == other.hasDirection());
      if (hasDirection()) {
        result = result && direction_ == other.direction_;
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
      }
      if (hasX()) {
        hash = (37 * hash) + X_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getX()));
      }
      if (hasY()) {
        hash = (37 * hash) + Y_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getY()));
      }
      if (hasPicked()) {
        hash = (37 * hash) + PICKED_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getPicked());
      }
      if (hasDirection()) {
        hash = (37 * hash) + DIRECTION_FIELD_NUMBER;
        hash = (53 * hash) + direction_;
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static netGameNodeSDK.mirror.Mirror.MirrorState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static netGameNodeSDK.mirror.Mirror.MirrorState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static netGameNodeSDK.mirror.Mirror.MirrorState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static netGameNodeSDK.mirror.Mirror.MirrorState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static netGameNodeSDK.mirror.Mirror.MirrorState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static netGameNodeSDK.mirror.Mirror.MirrorState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static netGameNodeSDK.mirror.Mirror.MirrorState parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static netGameNodeSDK.mirror.Mirror.MirrorState parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static netGameNodeSDK.mirror.Mirror.MirrorState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static netGameNodeSDK.mirror.Mirror.MirrorState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(netGameNodeSDK.mirror.Mirror.MirrorState prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code netGameNodeSDK.mirror.MirrorState}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:netGameNodeSDK.mirror.MirrorState)
        netGameNodeSDK.mirror.Mirror.MirrorStateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return netGameNodeSDK.mirror.Mirror.internal_static_netGameNodeSDK_mirror_MirrorState_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return netGameNodeSDK.mirror.Mirror.internal_static_netGameNodeSDK_mirror_MirrorState_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                netGameNodeSDK.mirror.Mirror.MirrorState.class, netGameNodeSDK.mirror.Mirror.MirrorState.Builder.class);
      }

      // Construct using netGameNodeSDK.mirror.Mirror.MirrorState.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        x_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        y_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        picked_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        direction_ = 1;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return netGameNodeSDK.mirror.Mirror.internal_static_netGameNodeSDK_mirror_MirrorState_descriptor;
      }

      public netGameNodeSDK.mirror.Mirror.MirrorState getDefaultInstanceForType() {
        return netGameNodeSDK.mirror.Mirror.MirrorState.getDefaultInstance();
      }

      public netGameNodeSDK.mirror.Mirror.MirrorState build() {
        netGameNodeSDK.mirror.Mirror.MirrorState result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public netGameNodeSDK.mirror.Mirror.MirrorState buildPartial() {
        netGameNodeSDK.mirror.Mirror.MirrorState result = new netGameNodeSDK.mirror.Mirror.MirrorState(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.x_ = x_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.y_ = y_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.picked_ = picked_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.direction_ = direction_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof netGameNodeSDK.mirror.Mirror.MirrorState) {
          return mergeFrom((netGameNodeSDK.mirror.Mirror.MirrorState)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(netGameNodeSDK.mirror.Mirror.MirrorState other) {
        if (other == netGameNodeSDK.mirror.Mirror.MirrorState.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        if (other.hasPicked()) {
          setPicked(other.getPicked());
        }
        if (other.hasDirection()) {
          setDirection(other.getDirection());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          return false;
        }
        if (!hasX()) {
          return false;
        }
        if (!hasY()) {
          return false;
        }
        if (!hasPicked()) {
          return false;
        }
        if (!hasDirection()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        netGameNodeSDK.mirror.Mirror.MirrorState parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (netGameNodeSDK.mirror.Mirror.MirrorState) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required uint32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required uint32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private double x_ ;
      /**
       * <code>required double x = 2;</code>
       */
      public boolean hasX() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required double x = 2;</code>
       */
      public double getX() {
        return x_;
      }
      /**
       * <code>required double x = 2;</code>
       */
      public Builder setX(double value) {
        bitField0_ |= 0x00000002;
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double x = 2;</code>
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000002);
        x_ = 0D;
        onChanged();
        return this;
      }

      private double y_ ;
      /**
       * <code>required double y = 3;</code>
       */
      public boolean hasY() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required double y = 3;</code>
       */
      public double getY() {
        return y_;
      }
      /**
       * <code>required double y = 3;</code>
       */
      public Builder setY(double value) {
        bitField0_ |= 0x00000004;
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double y = 3;</code>
       */
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000004);
        y_ = 0D;
        onChanged();
        return this;
      }

      private boolean picked_ ;
      /**
       * <code>required bool picked = 4;</code>
       */
      public boolean hasPicked() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required bool picked = 4;</code>
       */
      public boolean getPicked() {
        return picked_;
      }
      /**
       * <code>required bool picked = 4;</code>
       */
      public Builder setPicked(boolean value) {
        bitField0_ |= 0x00000008;
        picked_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool picked = 4;</code>
       */
      public Builder clearPicked() {
        bitField0_ = (bitField0_ & ~0x00000008);
        picked_ = false;
        onChanged();
        return this;
      }

      private int direction_ = 1;
      /**
       * <code>required .netGameNodeSDK.mirror.MirrorState.Direction direction = 5;</code>
       */
      public boolean hasDirection() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required .netGameNodeSDK.mirror.MirrorState.Direction direction = 5;</code>
       */
      public netGameNodeSDK.mirror.Mirror.MirrorState.Direction getDirection() {
        netGameNodeSDK.mirror.Mirror.MirrorState.Direction result = netGameNodeSDK.mirror.Mirror.MirrorState.Direction.valueOf(direction_);
        return result == null ? netGameNodeSDK.mirror.Mirror.MirrorState.Direction.SLASH : result;
      }
      /**
       * <code>required .netGameNodeSDK.mirror.MirrorState.Direction direction = 5;</code>
       */
      public Builder setDirection(netGameNodeSDK.mirror.Mirror.MirrorState.Direction value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        direction_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .netGameNodeSDK.mirror.MirrorState.Direction direction = 5;</code>
       */
      public Builder clearDirection() {
        bitField0_ = (bitField0_ & ~0x00000010);
        direction_ = 1;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:netGameNodeSDK.mirror.MirrorState)
    }

    // @@protoc_insertion_point(class_scope:netGameNodeSDK.mirror.MirrorState)
    private static final netGameNodeSDK.mirror.Mirror.MirrorState DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new netGameNodeSDK.mirror.Mirror.MirrorState();
    }

    public static netGameNodeSDK.mirror.Mirror.MirrorState getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<MirrorState>
        PARSER = new com.google.protobuf.AbstractParser<MirrorState>() {
      public MirrorState parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MirrorState(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MirrorState> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MirrorState> getParserForType() {
      return PARSER;
    }

    public netGameNodeSDK.mirror.Mirror.MirrorState getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_netGameNodeSDK_mirror_MirrorState_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_netGameNodeSDK_mirror_MirrorState_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014mirror.proto\022\025netGameNodeSDK.mirror\"\250\001" +
      "\n\013MirrorState\022\n\n\002id\030\001 \002(\r\022\t\n\001x\030\002 \002(\001\022\t\n\001" +
      "y\030\003 \002(\001\022\016\n\006picked\030\004 \002(\010\022?\n\tdirection\030\005 \002" +
      "(\0162,.netGameNodeSDK.mirror.MirrorState.D" +
      "irection\"&\n\tDirection\022\t\n\005SLASH\020\001\022\016\n\nBACK" +
      "_SLACK\020\002"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_netGameNodeSDK_mirror_MirrorState_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_netGameNodeSDK_mirror_MirrorState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_netGameNodeSDK_mirror_MirrorState_descriptor,
        new java.lang.String[] { "Id", "X", "Y", "Picked", "Direction", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
