// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: handshake.proto

package mirrorWar.handshake;

public final class Handshake {
  private Handshake() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ClientHandshakeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mirrorWar.handshake.ClientHandshake)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint32 updatePort = 1;</code>
     */
    boolean hasUpdatePort();
    /**
     * <code>required uint32 updatePort = 1;</code>
     */
    int getUpdatePort();
  }
  /**
   * Protobuf type {@code mirrorWar.handshake.ClientHandshake}
   */
  public  static final class ClientHandshake extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:mirrorWar.handshake.ClientHandshake)
      ClientHandshakeOrBuilder {
    // Use ClientHandshake.newBuilder() to construct.
    private ClientHandshake(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ClientHandshake() {
      updatePort_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ClientHandshake(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              updatePort_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mirrorWar.handshake.Handshake.internal_static_mirrorWar_handshake_ClientHandshake_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mirrorWar.handshake.Handshake.internal_static_mirrorWar_handshake_ClientHandshake_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              mirrorWar.handshake.Handshake.ClientHandshake.class, mirrorWar.handshake.Handshake.ClientHandshake.Builder.class);
    }

    private int bitField0_;
    public static final int UPDATEPORT_FIELD_NUMBER = 1;
    private int updatePort_;
    /**
     * <code>required uint32 updatePort = 1;</code>
     */
    public boolean hasUpdatePort() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 updatePort = 1;</code>
     */
    public int getUpdatePort() {
      return updatePort_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUpdatePort()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, updatePort_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, updatePort_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof mirrorWar.handshake.Handshake.ClientHandshake)) {
        return super.equals(obj);
      }
      mirrorWar.handshake.Handshake.ClientHandshake other = (mirrorWar.handshake.Handshake.ClientHandshake) obj;

      boolean result = true;
      result = result && (hasUpdatePort() == other.hasUpdatePort());
      if (hasUpdatePort()) {
        result = result && (getUpdatePort()
            == other.getUpdatePort());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasUpdatePort()) {
        hash = (37 * hash) + UPDATEPORT_FIELD_NUMBER;
        hash = (53 * hash) + getUpdatePort();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static mirrorWar.handshake.Handshake.ClientHandshake parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mirrorWar.handshake.Handshake.ClientHandshake parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mirrorWar.handshake.Handshake.ClientHandshake parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mirrorWar.handshake.Handshake.ClientHandshake parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mirrorWar.handshake.Handshake.ClientHandshake parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mirrorWar.handshake.Handshake.ClientHandshake parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static mirrorWar.handshake.Handshake.ClientHandshake parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static mirrorWar.handshake.Handshake.ClientHandshake parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static mirrorWar.handshake.Handshake.ClientHandshake parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mirrorWar.handshake.Handshake.ClientHandshake parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(mirrorWar.handshake.Handshake.ClientHandshake prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mirrorWar.handshake.ClientHandshake}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:mirrorWar.handshake.ClientHandshake)
        mirrorWar.handshake.Handshake.ClientHandshakeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return mirrorWar.handshake.Handshake.internal_static_mirrorWar_handshake_ClientHandshake_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return mirrorWar.handshake.Handshake.internal_static_mirrorWar_handshake_ClientHandshake_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                mirrorWar.handshake.Handshake.ClientHandshake.class, mirrorWar.handshake.Handshake.ClientHandshake.Builder.class);
      }

      // Construct using mirrorWar.handshake.Handshake.ClientHandshake.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        updatePort_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return mirrorWar.handshake.Handshake.internal_static_mirrorWar_handshake_ClientHandshake_descriptor;
      }

      public mirrorWar.handshake.Handshake.ClientHandshake getDefaultInstanceForType() {
        return mirrorWar.handshake.Handshake.ClientHandshake.getDefaultInstance();
      }

      public mirrorWar.handshake.Handshake.ClientHandshake build() {
        mirrorWar.handshake.Handshake.ClientHandshake result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public mirrorWar.handshake.Handshake.ClientHandshake buildPartial() {
        mirrorWar.handshake.Handshake.ClientHandshake result = new mirrorWar.handshake.Handshake.ClientHandshake(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.updatePort_ = updatePort_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof mirrorWar.handshake.Handshake.ClientHandshake) {
          return mergeFrom((mirrorWar.handshake.Handshake.ClientHandshake)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(mirrorWar.handshake.Handshake.ClientHandshake other) {
        if (other == mirrorWar.handshake.Handshake.ClientHandshake.getDefaultInstance()) return this;
        if (other.hasUpdatePort()) {
          setUpdatePort(other.getUpdatePort());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUpdatePort()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        mirrorWar.handshake.Handshake.ClientHandshake parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (mirrorWar.handshake.Handshake.ClientHandshake) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int updatePort_ ;
      /**
       * <code>required uint32 updatePort = 1;</code>
       */
      public boolean hasUpdatePort() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 updatePort = 1;</code>
       */
      public int getUpdatePort() {
        return updatePort_;
      }
      /**
       * <code>required uint32 updatePort = 1;</code>
       */
      public Builder setUpdatePort(int value) {
        bitField0_ |= 0x00000001;
        updatePort_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 updatePort = 1;</code>
       */
      public Builder clearUpdatePort() {
        bitField0_ = (bitField0_ & ~0x00000001);
        updatePort_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:mirrorWar.handshake.ClientHandshake)
    }

    // @@protoc_insertion_point(class_scope:mirrorWar.handshake.ClientHandshake)
    private static final mirrorWar.handshake.Handshake.ClientHandshake DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new mirrorWar.handshake.Handshake.ClientHandshake();
    }

    public static mirrorWar.handshake.Handshake.ClientHandshake getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ClientHandshake>
        PARSER = new com.google.protobuf.AbstractParser<ClientHandshake>() {
      public ClientHandshake parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ClientHandshake(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ClientHandshake> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ClientHandshake> getParserForType() {
      return PARSER;
    }

    public mirrorWar.handshake.Handshake.ClientHandshake getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ServerHandshakeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mirrorWar.handshake.ServerHandshake)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 clientId = 1;</code>
     */
    boolean hasClientId();
    /**
     * <code>required int32 clientId = 1;</code>
     */
    int getClientId();

    /**
     * <code>required uint32 commandPort = 2;</code>
     */
    boolean hasCommandPort();
    /**
     * <code>required uint32 commandPort = 2;</code>
     */
    int getCommandPort();
  }
  /**
   * Protobuf type {@code mirrorWar.handshake.ServerHandshake}
   */
  public  static final class ServerHandshake extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:mirrorWar.handshake.ServerHandshake)
      ServerHandshakeOrBuilder {
    // Use ServerHandshake.newBuilder() to construct.
    private ServerHandshake(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ServerHandshake() {
      clientId_ = 0;
      commandPort_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ServerHandshake(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              clientId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              commandPort_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mirrorWar.handshake.Handshake.internal_static_mirrorWar_handshake_ServerHandshake_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mirrorWar.handshake.Handshake.internal_static_mirrorWar_handshake_ServerHandshake_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              mirrorWar.handshake.Handshake.ServerHandshake.class, mirrorWar.handshake.Handshake.ServerHandshake.Builder.class);
    }

    private int bitField0_;
    public static final int CLIENTID_FIELD_NUMBER = 1;
    private int clientId_;
    /**
     * <code>required int32 clientId = 1;</code>
     */
    public boolean hasClientId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 clientId = 1;</code>
     */
    public int getClientId() {
      return clientId_;
    }

    public static final int COMMANDPORT_FIELD_NUMBER = 2;
    private int commandPort_;
    /**
     * <code>required uint32 commandPort = 2;</code>
     */
    public boolean hasCommandPort() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint32 commandPort = 2;</code>
     */
    public int getCommandPort() {
      return commandPort_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasClientId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCommandPort()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, clientId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, commandPort_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, clientId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, commandPort_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof mirrorWar.handshake.Handshake.ServerHandshake)) {
        return super.equals(obj);
      }
      mirrorWar.handshake.Handshake.ServerHandshake other = (mirrorWar.handshake.Handshake.ServerHandshake) obj;

      boolean result = true;
      result = result && (hasClientId() == other.hasClientId());
      if (hasClientId()) {
        result = result && (getClientId()
            == other.getClientId());
      }
      result = result && (hasCommandPort() == other.hasCommandPort());
      if (hasCommandPort()) {
        result = result && (getCommandPort()
            == other.getCommandPort());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasClientId()) {
        hash = (37 * hash) + CLIENTID_FIELD_NUMBER;
        hash = (53 * hash) + getClientId();
      }
      if (hasCommandPort()) {
        hash = (37 * hash) + COMMANDPORT_FIELD_NUMBER;
        hash = (53 * hash) + getCommandPort();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static mirrorWar.handshake.Handshake.ServerHandshake parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mirrorWar.handshake.Handshake.ServerHandshake parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mirrorWar.handshake.Handshake.ServerHandshake parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mirrorWar.handshake.Handshake.ServerHandshake parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mirrorWar.handshake.Handshake.ServerHandshake parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mirrorWar.handshake.Handshake.ServerHandshake parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static mirrorWar.handshake.Handshake.ServerHandshake parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static mirrorWar.handshake.Handshake.ServerHandshake parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static mirrorWar.handshake.Handshake.ServerHandshake parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mirrorWar.handshake.Handshake.ServerHandshake parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(mirrorWar.handshake.Handshake.ServerHandshake prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mirrorWar.handshake.ServerHandshake}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:mirrorWar.handshake.ServerHandshake)
        mirrorWar.handshake.Handshake.ServerHandshakeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return mirrorWar.handshake.Handshake.internal_static_mirrorWar_handshake_ServerHandshake_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return mirrorWar.handshake.Handshake.internal_static_mirrorWar_handshake_ServerHandshake_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                mirrorWar.handshake.Handshake.ServerHandshake.class, mirrorWar.handshake.Handshake.ServerHandshake.Builder.class);
      }

      // Construct using mirrorWar.handshake.Handshake.ServerHandshake.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        clientId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        commandPort_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return mirrorWar.handshake.Handshake.internal_static_mirrorWar_handshake_ServerHandshake_descriptor;
      }

      public mirrorWar.handshake.Handshake.ServerHandshake getDefaultInstanceForType() {
        return mirrorWar.handshake.Handshake.ServerHandshake.getDefaultInstance();
      }

      public mirrorWar.handshake.Handshake.ServerHandshake build() {
        mirrorWar.handshake.Handshake.ServerHandshake result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public mirrorWar.handshake.Handshake.ServerHandshake buildPartial() {
        mirrorWar.handshake.Handshake.ServerHandshake result = new mirrorWar.handshake.Handshake.ServerHandshake(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.clientId_ = clientId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.commandPort_ = commandPort_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof mirrorWar.handshake.Handshake.ServerHandshake) {
          return mergeFrom((mirrorWar.handshake.Handshake.ServerHandshake)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(mirrorWar.handshake.Handshake.ServerHandshake other) {
        if (other == mirrorWar.handshake.Handshake.ServerHandshake.getDefaultInstance()) return this;
        if (other.hasClientId()) {
          setClientId(other.getClientId());
        }
        if (other.hasCommandPort()) {
          setCommandPort(other.getCommandPort());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasClientId()) {
          return false;
        }
        if (!hasCommandPort()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        mirrorWar.handshake.Handshake.ServerHandshake parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (mirrorWar.handshake.Handshake.ServerHandshake) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int clientId_ ;
      /**
       * <code>required int32 clientId = 1;</code>
       */
      public boolean hasClientId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 clientId = 1;</code>
       */
      public int getClientId() {
        return clientId_;
      }
      /**
       * <code>required int32 clientId = 1;</code>
       */
      public Builder setClientId(int value) {
        bitField0_ |= 0x00000001;
        clientId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 clientId = 1;</code>
       */
      public Builder clearClientId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        clientId_ = 0;
        onChanged();
        return this;
      }

      private int commandPort_ ;
      /**
       * <code>required uint32 commandPort = 2;</code>
       */
      public boolean hasCommandPort() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint32 commandPort = 2;</code>
       */
      public int getCommandPort() {
        return commandPort_;
      }
      /**
       * <code>required uint32 commandPort = 2;</code>
       */
      public Builder setCommandPort(int value) {
        bitField0_ |= 0x00000002;
        commandPort_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 commandPort = 2;</code>
       */
      public Builder clearCommandPort() {
        bitField0_ = (bitField0_ & ~0x00000002);
        commandPort_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:mirrorWar.handshake.ServerHandshake)
    }

    // @@protoc_insertion_point(class_scope:mirrorWar.handshake.ServerHandshake)
    private static final mirrorWar.handshake.Handshake.ServerHandshake DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new mirrorWar.handshake.Handshake.ServerHandshake();
    }

    public static mirrorWar.handshake.Handshake.ServerHandshake getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ServerHandshake>
        PARSER = new com.google.protobuf.AbstractParser<ServerHandshake>() {
      public ServerHandshake parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ServerHandshake(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ServerHandshake> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ServerHandshake> getParserForType() {
      return PARSER;
    }

    public mirrorWar.handshake.Handshake.ServerHandshake getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mirrorWar_handshake_ClientHandshake_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mirrorWar_handshake_ClientHandshake_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mirrorWar_handshake_ServerHandshake_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mirrorWar_handshake_ServerHandshake_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017handshake.proto\022\023mirrorWar.handshake\"%" +
      "\n\017ClientHandshake\022\022\n\nupdatePort\030\001 \002(\r\"8\n" +
      "\017ServerHandshake\022\020\n\010clientId\030\001 \002(\005\022\023\n\013co" +
      "mmandPort\030\002 \002(\r"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_mirrorWar_handshake_ClientHandshake_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mirrorWar_handshake_ClientHandshake_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mirrorWar_handshake_ClientHandshake_descriptor,
        new java.lang.String[] { "UpdatePort", });
    internal_static_mirrorWar_handshake_ServerHandshake_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_mirrorWar_handshake_ServerHandshake_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mirrorWar_handshake_ServerHandshake_descriptor,
        new java.lang.String[] { "ClientId", "CommandPort", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
