// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: input.proto

package mirrorWar.input;

public final class InputOuterClass {
  private InputOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface InputOrBuilder extends
      // @@protoc_insertion_point(interface_extends:netGameNodeSDK.input.Input)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .netGameNodeSDK.key.Key key = 1;</code>
     */
    boolean hasKey();
    /**
     * <code>optional .netGameNodeSDK.key.Key key = 1;</code>
     */
    mirrorWar.key.KeyOuterClass.Key getKey();
    /**
     * <code>optional .netGameNodeSDK.key.Key key = 1;</code>
     */
    mirrorWar.key.KeyOuterClass.KeyOrBuilder getKeyOrBuilder();

    public mirrorWar.input.InputOuterClass.Input.InputCase getInputCase();
  }
  /**
   * Protobuf type {@code netGameNodeSDK.input.Input}
   */
  public  static final class Input extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:netGameNodeSDK.input.Input)
      InputOrBuilder {
    // Use Input.newBuilder() to construct.
    private Input(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Input() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Input(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              mirrorWar.key.KeyOuterClass.Key.Builder subBuilder = null;
              if (inputCase_ == 1) {
                subBuilder = ((mirrorWar.key.KeyOuterClass.Key) input_).toBuilder();
              }
              input_ =
                  input.readMessage(mirrorWar.key.KeyOuterClass.Key.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((mirrorWar.key.KeyOuterClass.Key) input_);
                input_ = subBuilder.buildPartial();
              }
              inputCase_ = 1;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mirrorWar.input.InputOuterClass.internal_static_netGameNodeSDK_input_Input_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mirrorWar.input.InputOuterClass.internal_static_netGameNodeSDK_input_Input_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              mirrorWar.input.InputOuterClass.Input.class, mirrorWar.input.InputOuterClass.Input.Builder.class);
    }

    private int bitField0_;
    private int inputCase_ = 0;
    private java.lang.Object input_;
    public enum InputCase
        implements com.google.protobuf.Internal.EnumLite {
      KEY(1),
      INPUT_NOT_SET(0);
      private final int value;
      private InputCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static InputCase valueOf(int value) {
        return forNumber(value);
      }

      public static InputCase forNumber(int value) {
        switch (value) {
          case 1: return KEY;
          case 0: return INPUT_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public InputCase
    getInputCase() {
      return InputCase.forNumber(
          inputCase_);
    }

    public static final int KEY_FIELD_NUMBER = 1;
    /**
     * <code>optional .netGameNodeSDK.key.Key key = 1;</code>
     */
    public boolean hasKey() {
      return inputCase_ == 1;
    }
    /**
     * <code>optional .netGameNodeSDK.key.Key key = 1;</code>
     */
    public mirrorWar.key.KeyOuterClass.Key getKey() {
      if (inputCase_ == 1) {
         return (mirrorWar.key.KeyOuterClass.Key) input_;
      }
      return mirrorWar.key.KeyOuterClass.Key.getDefaultInstance();
    }
    /**
     * <code>optional .netGameNodeSDK.key.Key key = 1;</code>
     */
    public mirrorWar.key.KeyOuterClass.KeyOrBuilder getKeyOrBuilder() {
      if (inputCase_ == 1) {
         return (mirrorWar.key.KeyOuterClass.Key) input_;
      }
      return mirrorWar.key.KeyOuterClass.Key.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (hasKey()) {
        if (!getKey().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (inputCase_ == 1) {
        output.writeMessage(1, (mirrorWar.key.KeyOuterClass.Key) input_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (inputCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (mirrorWar.key.KeyOuterClass.Key) input_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof mirrorWar.input.InputOuterClass.Input)) {
        return super.equals(obj);
      }
      mirrorWar.input.InputOuterClass.Input other = (mirrorWar.input.InputOuterClass.Input) obj;

      boolean result = true;
      result = result && getInputCase().equals(
          other.getInputCase());
      if (!result) return false;
      switch (inputCase_) {
        case 1:
          result = result && getKey()
              .equals(other.getKey());
          break;
        case 0:
        default:
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      switch (inputCase_) {
        case 1:
          hash = (37 * hash) + KEY_FIELD_NUMBER;
          hash = (53 * hash) + getKey().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static mirrorWar.input.InputOuterClass.Input parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mirrorWar.input.InputOuterClass.Input parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mirrorWar.input.InputOuterClass.Input parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mirrorWar.input.InputOuterClass.Input parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mirrorWar.input.InputOuterClass.Input parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mirrorWar.input.InputOuterClass.Input parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static mirrorWar.input.InputOuterClass.Input parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static mirrorWar.input.InputOuterClass.Input parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static mirrorWar.input.InputOuterClass.Input parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mirrorWar.input.InputOuterClass.Input parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(mirrorWar.input.InputOuterClass.Input prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code netGameNodeSDK.input.Input}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:netGameNodeSDK.input.Input)
        mirrorWar.input.InputOuterClass.InputOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return mirrorWar.input.InputOuterClass.internal_static_netGameNodeSDK_input_Input_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return mirrorWar.input.InputOuterClass.internal_static_netGameNodeSDK_input_Input_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                mirrorWar.input.InputOuterClass.Input.class, mirrorWar.input.InputOuterClass.Input.Builder.class);
      }

      // Construct using netGameNodeSDK.input.InputOuterClass.Input.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        inputCase_ = 0;
        input_ = null;
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return mirrorWar.input.InputOuterClass.internal_static_netGameNodeSDK_input_Input_descriptor;
      }

      public mirrorWar.input.InputOuterClass.Input getDefaultInstanceForType() {
        return mirrorWar.input.InputOuterClass.Input.getDefaultInstance();
      }

      public mirrorWar.input.InputOuterClass.Input build() {
        mirrorWar.input.InputOuterClass.Input result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public mirrorWar.input.InputOuterClass.Input buildPartial() {
        mirrorWar.input.InputOuterClass.Input result = new mirrorWar.input.InputOuterClass.Input(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (inputCase_ == 1) {
          if (keyBuilder_ == null) {
            result.input_ = input_;
          } else {
            result.input_ = keyBuilder_.build();
          }
        }
        result.bitField0_ = to_bitField0_;
        result.inputCase_ = inputCase_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof mirrorWar.input.InputOuterClass.Input) {
          return mergeFrom((mirrorWar.input.InputOuterClass.Input)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(mirrorWar.input.InputOuterClass.Input other) {
        if (other == mirrorWar.input.InputOuterClass.Input.getDefaultInstance()) return this;
        switch (other.getInputCase()) {
          case KEY: {
            mergeKey(other.getKey());
            break;
          }
          case INPUT_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (hasKey()) {
          if (!getKey().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        mirrorWar.input.InputOuterClass.Input parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (mirrorWar.input.InputOuterClass.Input) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int inputCase_ = 0;
      private java.lang.Object input_;
      public InputCase
          getInputCase() {
        return InputCase.forNumber(
            inputCase_);
      }

      public Builder clearInput() {
        inputCase_ = 0;
        input_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private com.google.protobuf.SingleFieldBuilderV3<
          mirrorWar.key.KeyOuterClass.Key, mirrorWar.key.KeyOuterClass.Key.Builder, mirrorWar.key.KeyOuterClass.KeyOrBuilder> keyBuilder_;
      /**
       * <code>optional .netGameNodeSDK.key.Key key = 1;</code>
       */
      public boolean hasKey() {
        return inputCase_ == 1;
      }
      /**
       * <code>optional .netGameNodeSDK.key.Key key = 1;</code>
       */
      public mirrorWar.key.KeyOuterClass.Key getKey() {
        if (keyBuilder_ == null) {
          if (inputCase_ == 1) {
            return (mirrorWar.key.KeyOuterClass.Key) input_;
          }
          return mirrorWar.key.KeyOuterClass.Key.getDefaultInstance();
        } else {
          if (inputCase_ == 1) {
            return keyBuilder_.getMessage();
          }
          return mirrorWar.key.KeyOuterClass.Key.getDefaultInstance();
        }
      }
      /**
       * <code>optional .netGameNodeSDK.key.Key key = 1;</code>
       */
      public Builder setKey(mirrorWar.key.KeyOuterClass.Key value) {
        if (keyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          input_ = value;
          onChanged();
        } else {
          keyBuilder_.setMessage(value);
        }
        inputCase_ = 1;
        return this;
      }
      /**
       * <code>optional .netGameNodeSDK.key.Key key = 1;</code>
       */
      public Builder setKey(
          mirrorWar.key.KeyOuterClass.Key.Builder builderForValue) {
        if (keyBuilder_ == null) {
          input_ = builderForValue.build();
          onChanged();
        } else {
          keyBuilder_.setMessage(builderForValue.build());
        }
        inputCase_ = 1;
        return this;
      }
      /**
       * <code>optional .netGameNodeSDK.key.Key key = 1;</code>
       */
      public Builder mergeKey(mirrorWar.key.KeyOuterClass.Key value) {
        if (keyBuilder_ == null) {
          if (inputCase_ == 1 &&
              input_ != mirrorWar.key.KeyOuterClass.Key.getDefaultInstance()) {
            input_ = mirrorWar.key.KeyOuterClass.Key.newBuilder((mirrorWar.key.KeyOuterClass.Key) input_)
                .mergeFrom(value).buildPartial();
          } else {
            input_ = value;
          }
          onChanged();
        } else {
          if (inputCase_ == 1) {
            keyBuilder_.mergeFrom(value);
          }
          keyBuilder_.setMessage(value);
        }
        inputCase_ = 1;
        return this;
      }
      /**
       * <code>optional .netGameNodeSDK.key.Key key = 1;</code>
       */
      public Builder clearKey() {
        if (keyBuilder_ == null) {
          if (inputCase_ == 1) {
            inputCase_ = 0;
            input_ = null;
            onChanged();
          }
        } else {
          if (inputCase_ == 1) {
            inputCase_ = 0;
            input_ = null;
          }
          keyBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .netGameNodeSDK.key.Key key = 1;</code>
       */
      public mirrorWar.key.KeyOuterClass.Key.Builder getKeyBuilder() {
        return getKeyFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .netGameNodeSDK.key.Key key = 1;</code>
       */
      public mirrorWar.key.KeyOuterClass.KeyOrBuilder getKeyOrBuilder() {
        if ((inputCase_ == 1) && (keyBuilder_ != null)) {
          return keyBuilder_.getMessageOrBuilder();
        } else {
          if (inputCase_ == 1) {
            return (mirrorWar.key.KeyOuterClass.Key) input_;
          }
          return mirrorWar.key.KeyOuterClass.Key.getDefaultInstance();
        }
      }
      /**
       * <code>optional .netGameNodeSDK.key.Key key = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          mirrorWar.key.KeyOuterClass.Key, mirrorWar.key.KeyOuterClass.Key.Builder, mirrorWar.key.KeyOuterClass.KeyOrBuilder> 
          getKeyFieldBuilder() {
        if (keyBuilder_ == null) {
          if (!(inputCase_ == 1)) {
            input_ = mirrorWar.key.KeyOuterClass.Key.getDefaultInstance();
          }
          keyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              mirrorWar.key.KeyOuterClass.Key, mirrorWar.key.KeyOuterClass.Key.Builder, mirrorWar.key.KeyOuterClass.KeyOrBuilder>(
                  (mirrorWar.key.KeyOuterClass.Key) input_,
                  getParentForChildren(),
                  isClean());
          input_ = null;
        }
        inputCase_ = 1;
        onChanged();;
        return keyBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:netGameNodeSDK.input.Input)
    }

    // @@protoc_insertion_point(class_scope:netGameNodeSDK.input.Input)
    private static final mirrorWar.input.InputOuterClass.Input DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new mirrorWar.input.InputOuterClass.Input();
    }

    public static mirrorWar.input.InputOuterClass.Input getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Input>
        PARSER = new com.google.protobuf.AbstractParser<Input>() {
      public Input parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Input(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Input> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Input> getParserForType() {
      return PARSER;
    }

    public mirrorWar.input.InputOuterClass.Input getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface InputsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:netGameNodeSDK.input.Inputs)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 clientId = 1;</code>
     */
    boolean hasClientId();
    /**
     * <code>required int32 clientId = 1;</code>
     */
    int getClientId();

    /**
     * <code>repeated .netGameNodeSDK.input.Input inputs = 2;</code>
     */
    java.util.List<mirrorWar.input.InputOuterClass.Input> 
        getInputsList();
    /**
     * <code>repeated .netGameNodeSDK.input.Input inputs = 2;</code>
     */
    mirrorWar.input.InputOuterClass.Input getInputs(int index);
    /**
     * <code>repeated .netGameNodeSDK.input.Input inputs = 2;</code>
     */
    int getInputsCount();
    /**
     * <code>repeated .netGameNodeSDK.input.Input inputs = 2;</code>
     */
    java.util.List<? extends mirrorWar.input.InputOuterClass.InputOrBuilder> 
        getInputsOrBuilderList();
    /**
     * <code>repeated .netGameNodeSDK.input.Input inputs = 2;</code>
     */
    mirrorWar.input.InputOuterClass.InputOrBuilder getInputsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code netGameNodeSDK.input.Inputs}
   */
  public  static final class Inputs extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:netGameNodeSDK.input.Inputs)
      InputsOrBuilder {
    // Use Inputs.newBuilder() to construct.
    private Inputs(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Inputs() {
      clientId_ = 0;
      inputs_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Inputs(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              clientId_ = input.readInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                inputs_ = new java.util.ArrayList<mirrorWar.input.InputOuterClass.Input>();
                mutable_bitField0_ |= 0x00000002;
              }
              inputs_.add(
                  input.readMessage(mirrorWar.input.InputOuterClass.Input.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          inputs_ = java.util.Collections.unmodifiableList(inputs_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mirrorWar.input.InputOuterClass.internal_static_netGameNodeSDK_input_Inputs_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mirrorWar.input.InputOuterClass.internal_static_netGameNodeSDK_input_Inputs_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              mirrorWar.input.InputOuterClass.Inputs.class, mirrorWar.input.InputOuterClass.Inputs.Builder.class);
    }

    private int bitField0_;
    public static final int CLIENTID_FIELD_NUMBER = 1;
    private int clientId_;
    /**
     * <code>required int32 clientId = 1;</code>
     */
    public boolean hasClientId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 clientId = 1;</code>
     */
    public int getClientId() {
      return clientId_;
    }

    public static final int INPUTS_FIELD_NUMBER = 2;
    private java.util.List<mirrorWar.input.InputOuterClass.Input> inputs_;
    /**
     * <code>repeated .netGameNodeSDK.input.Input inputs = 2;</code>
     */
    public java.util.List<mirrorWar.input.InputOuterClass.Input> getInputsList() {
      return inputs_;
    }
    /**
     * <code>repeated .netGameNodeSDK.input.Input inputs = 2;</code>
     */
    public java.util.List<? extends mirrorWar.input.InputOuterClass.InputOrBuilder> 
        getInputsOrBuilderList() {
      return inputs_;
    }
    /**
     * <code>repeated .netGameNodeSDK.input.Input inputs = 2;</code>
     */
    public int getInputsCount() {
      return inputs_.size();
    }
    /**
     * <code>repeated .netGameNodeSDK.input.Input inputs = 2;</code>
     */
    public mirrorWar.input.InputOuterClass.Input getInputs(int index) {
      return inputs_.get(index);
    }
    /**
     * <code>repeated .netGameNodeSDK.input.Input inputs = 2;</code>
     */
    public mirrorWar.input.InputOuterClass.InputOrBuilder getInputsOrBuilder(
        int index) {
      return inputs_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasClientId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getInputsCount(); i++) {
        if (!getInputs(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, clientId_);
      }
      for (int i = 0; i < inputs_.size(); i++) {
        output.writeMessage(2, inputs_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, clientId_);
      }
      for (int i = 0; i < inputs_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, inputs_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof mirrorWar.input.InputOuterClass.Inputs)) {
        return super.equals(obj);
      }
      mirrorWar.input.InputOuterClass.Inputs other = (mirrorWar.input.InputOuterClass.Inputs) obj;

      boolean result = true;
      result = result && (hasClientId() == other.hasClientId());
      if (hasClientId()) {
        result = result && (getClientId()
            == other.getClientId());
      }
      result = result && getInputsList()
          .equals(other.getInputsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasClientId()) {
        hash = (37 * hash) + CLIENTID_FIELD_NUMBER;
        hash = (53 * hash) + getClientId();
      }
      if (getInputsCount() > 0) {
        hash = (37 * hash) + INPUTS_FIELD_NUMBER;
        hash = (53 * hash) + getInputsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static mirrorWar.input.InputOuterClass.Inputs parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mirrorWar.input.InputOuterClass.Inputs parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mirrorWar.input.InputOuterClass.Inputs parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mirrorWar.input.InputOuterClass.Inputs parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mirrorWar.input.InputOuterClass.Inputs parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mirrorWar.input.InputOuterClass.Inputs parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static mirrorWar.input.InputOuterClass.Inputs parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static mirrorWar.input.InputOuterClass.Inputs parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static mirrorWar.input.InputOuterClass.Inputs parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mirrorWar.input.InputOuterClass.Inputs parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(mirrorWar.input.InputOuterClass.Inputs prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code netGameNodeSDK.input.Inputs}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:netGameNodeSDK.input.Inputs)
        mirrorWar.input.InputOuterClass.InputsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return mirrorWar.input.InputOuterClass.internal_static_netGameNodeSDK_input_Inputs_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return mirrorWar.input.InputOuterClass.internal_static_netGameNodeSDK_input_Inputs_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                mirrorWar.input.InputOuterClass.Inputs.class, mirrorWar.input.InputOuterClass.Inputs.Builder.class);
      }

      // Construct using netGameNodeSDK.input.InputOuterClass.Inputs.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getInputsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        clientId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (inputsBuilder_ == null) {
          inputs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          inputsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return mirrorWar.input.InputOuterClass.internal_static_netGameNodeSDK_input_Inputs_descriptor;
      }

      public mirrorWar.input.InputOuterClass.Inputs getDefaultInstanceForType() {
        return mirrorWar.input.InputOuterClass.Inputs.getDefaultInstance();
      }

      public mirrorWar.input.InputOuterClass.Inputs build() {
        mirrorWar.input.InputOuterClass.Inputs result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public mirrorWar.input.InputOuterClass.Inputs buildPartial() {
        mirrorWar.input.InputOuterClass.Inputs result = new mirrorWar.input.InputOuterClass.Inputs(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.clientId_ = clientId_;
        if (inputsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            inputs_ = java.util.Collections.unmodifiableList(inputs_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.inputs_ = inputs_;
        } else {
          result.inputs_ = inputsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof mirrorWar.input.InputOuterClass.Inputs) {
          return mergeFrom((mirrorWar.input.InputOuterClass.Inputs)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(mirrorWar.input.InputOuterClass.Inputs other) {
        if (other == mirrorWar.input.InputOuterClass.Inputs.getDefaultInstance()) return this;
        if (other.hasClientId()) {
          setClientId(other.getClientId());
        }
        if (inputsBuilder_ == null) {
          if (!other.inputs_.isEmpty()) {
            if (inputs_.isEmpty()) {
              inputs_ = other.inputs_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureInputsIsMutable();
              inputs_.addAll(other.inputs_);
            }
            onChanged();
          }
        } else {
          if (!other.inputs_.isEmpty()) {
            if (inputsBuilder_.isEmpty()) {
              inputsBuilder_.dispose();
              inputsBuilder_ = null;
              inputs_ = other.inputs_;
              bitField0_ = (bitField0_ & ~0x00000002);
              inputsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getInputsFieldBuilder() : null;
            } else {
              inputsBuilder_.addAllMessages(other.inputs_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasClientId()) {
          return false;
        }
        for (int i = 0; i < getInputsCount(); i++) {
          if (!getInputs(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        mirrorWar.input.InputOuterClass.Inputs parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (mirrorWar.input.InputOuterClass.Inputs) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int clientId_ ;
      /**
       * <code>required int32 clientId = 1;</code>
       */
      public boolean hasClientId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 clientId = 1;</code>
       */
      public int getClientId() {
        return clientId_;
      }
      /**
       * <code>required int32 clientId = 1;</code>
       */
      public Builder setClientId(int value) {
        bitField0_ |= 0x00000001;
        clientId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 clientId = 1;</code>
       */
      public Builder clearClientId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        clientId_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<mirrorWar.input.InputOuterClass.Input> inputs_ =
        java.util.Collections.emptyList();
      private void ensureInputsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          inputs_ = new java.util.ArrayList<mirrorWar.input.InputOuterClass.Input>(inputs_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          mirrorWar.input.InputOuterClass.Input, mirrorWar.input.InputOuterClass.Input.Builder, mirrorWar.input.InputOuterClass.InputOrBuilder> inputsBuilder_;

      /**
       * <code>repeated .netGameNodeSDK.input.Input inputs = 2;</code>
       */
      public java.util.List<mirrorWar.input.InputOuterClass.Input> getInputsList() {
        if (inputsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(inputs_);
        } else {
          return inputsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .netGameNodeSDK.input.Input inputs = 2;</code>
       */
      public int getInputsCount() {
        if (inputsBuilder_ == null) {
          return inputs_.size();
        } else {
          return inputsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .netGameNodeSDK.input.Input inputs = 2;</code>
       */
      public mirrorWar.input.InputOuterClass.Input getInputs(int index) {
        if (inputsBuilder_ == null) {
          return inputs_.get(index);
        } else {
          return inputsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .netGameNodeSDK.input.Input inputs = 2;</code>
       */
      public Builder setInputs(
          int index, mirrorWar.input.InputOuterClass.Input value) {
        if (inputsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInputsIsMutable();
          inputs_.set(index, value);
          onChanged();
        } else {
          inputsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .netGameNodeSDK.input.Input inputs = 2;</code>
       */
      public Builder setInputs(
          int index, mirrorWar.input.InputOuterClass.Input.Builder builderForValue) {
        if (inputsBuilder_ == null) {
          ensureInputsIsMutable();
          inputs_.set(index, builderForValue.build());
          onChanged();
        } else {
          inputsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .netGameNodeSDK.input.Input inputs = 2;</code>
       */
      public Builder addInputs(mirrorWar.input.InputOuterClass.Input value) {
        if (inputsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInputsIsMutable();
          inputs_.add(value);
          onChanged();
        } else {
          inputsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .netGameNodeSDK.input.Input inputs = 2;</code>
       */
      public Builder addInputs(
          int index, mirrorWar.input.InputOuterClass.Input value) {
        if (inputsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInputsIsMutable();
          inputs_.add(index, value);
          onChanged();
        } else {
          inputsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .netGameNodeSDK.input.Input inputs = 2;</code>
       */
      public Builder addInputs(
          mirrorWar.input.InputOuterClass.Input.Builder builderForValue) {
        if (inputsBuilder_ == null) {
          ensureInputsIsMutable();
          inputs_.add(builderForValue.build());
          onChanged();
        } else {
          inputsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .netGameNodeSDK.input.Input inputs = 2;</code>
       */
      public Builder addInputs(
          int index, mirrorWar.input.InputOuterClass.Input.Builder builderForValue) {
        if (inputsBuilder_ == null) {
          ensureInputsIsMutable();
          inputs_.add(index, builderForValue.build());
          onChanged();
        } else {
          inputsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .netGameNodeSDK.input.Input inputs = 2;</code>
       */
      public Builder addAllInputs(
          java.lang.Iterable<? extends mirrorWar.input.InputOuterClass.Input> values) {
        if (inputsBuilder_ == null) {
          ensureInputsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, inputs_);
          onChanged();
        } else {
          inputsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .netGameNodeSDK.input.Input inputs = 2;</code>
       */
      public Builder clearInputs() {
        if (inputsBuilder_ == null) {
          inputs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          inputsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .netGameNodeSDK.input.Input inputs = 2;</code>
       */
      public Builder removeInputs(int index) {
        if (inputsBuilder_ == null) {
          ensureInputsIsMutable();
          inputs_.remove(index);
          onChanged();
        } else {
          inputsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .netGameNodeSDK.input.Input inputs = 2;</code>
       */
      public mirrorWar.input.InputOuterClass.Input.Builder getInputsBuilder(
          int index) {
        return getInputsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .netGameNodeSDK.input.Input inputs = 2;</code>
       */
      public mirrorWar.input.InputOuterClass.InputOrBuilder getInputsOrBuilder(
          int index) {
        if (inputsBuilder_ == null) {
          return inputs_.get(index);  } else {
          return inputsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .netGameNodeSDK.input.Input inputs = 2;</code>
       */
      public java.util.List<? extends mirrorWar.input.InputOuterClass.InputOrBuilder> 
           getInputsOrBuilderList() {
        if (inputsBuilder_ != null) {
          return inputsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(inputs_);
        }
      }
      /**
       * <code>repeated .netGameNodeSDK.input.Input inputs = 2;</code>
       */
      public mirrorWar.input.InputOuterClass.Input.Builder addInputsBuilder() {
        return getInputsFieldBuilder().addBuilder(
            mirrorWar.input.InputOuterClass.Input.getDefaultInstance());
      }
      /**
       * <code>repeated .netGameNodeSDK.input.Input inputs = 2;</code>
       */
      public mirrorWar.input.InputOuterClass.Input.Builder addInputsBuilder(
          int index) {
        return getInputsFieldBuilder().addBuilder(
            index, mirrorWar.input.InputOuterClass.Input.getDefaultInstance());
      }
      /**
       * <code>repeated .netGameNodeSDK.input.Input inputs = 2;</code>
       */
      public java.util.List<mirrorWar.input.InputOuterClass.Input.Builder> 
           getInputsBuilderList() {
        return getInputsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          mirrorWar.input.InputOuterClass.Input, mirrorWar.input.InputOuterClass.Input.Builder, mirrorWar.input.InputOuterClass.InputOrBuilder> 
          getInputsFieldBuilder() {
        if (inputsBuilder_ == null) {
          inputsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              mirrorWar.input.InputOuterClass.Input, mirrorWar.input.InputOuterClass.Input.Builder, mirrorWar.input.InputOuterClass.InputOrBuilder>(
                  inputs_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          inputs_ = null;
        }
        return inputsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:netGameNodeSDK.input.Inputs)
    }

    // @@protoc_insertion_point(class_scope:netGameNodeSDK.input.Inputs)
    private static final mirrorWar.input.InputOuterClass.Inputs DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new mirrorWar.input.InputOuterClass.Inputs();
    }

    public static mirrorWar.input.InputOuterClass.Inputs getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Inputs>
        PARSER = new com.google.protobuf.AbstractParser<Inputs>() {
      public Inputs parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Inputs(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Inputs> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Inputs> getParserForType() {
      return PARSER;
    }

    public mirrorWar.input.InputOuterClass.Inputs getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_netGameNodeSDK_input_Input_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_netGameNodeSDK_input_Input_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_netGameNodeSDK_input_Inputs_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_netGameNodeSDK_input_Inputs_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013input.proto\022\024netGameNodeSDK.input\032\tkey" +
      ".proto\"8\n\005Input\022&\n\003key\030\001 \001(\0132\027.netGameNo" +
      "deSDK.key.KeyH\000B\007\n\005input\"G\n\006Inputs\022\020\n\010cl" +
      "ientId\030\001 \002(\005\022+\n\006inputs\030\002 \003(\0132\033.netGameNo" +
      "deSDK.input.Input"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          mirrorWar.key.KeyOuterClass.getDescriptor(),
        }, assigner);
    internal_static_netGameNodeSDK_input_Input_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_netGameNodeSDK_input_Input_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_netGameNodeSDK_input_Input_descriptor,
        new java.lang.String[] { "Key", "Input", });
    internal_static_netGameNodeSDK_input_Inputs_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_netGameNodeSDK_input_Inputs_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_netGameNodeSDK_input_Inputs_descriptor,
        new java.lang.String[] { "ClientId", "Inputs", });
    mirrorWar.key.KeyOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
