// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gameReport.proto

package mirrorWar.gameReport;

public final class GameReport {
  private GameReport() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StatusOrBuilder extends
      // @@protoc_insertion_point(interface_extends:netGameNodeSDK.gameReport.Status)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 player0Life = 1;</code>
     */
    boolean hasPlayer0Life();
    /**
     * <code>required int32 player0Life = 1;</code>
     */
    int getPlayer0Life();

    /**
     * <code>required int32 player1Life = 2;</code>
     */
    boolean hasPlayer1Life();
    /**
     * <code>required int32 player1Life = 2;</code>
     */
    int getPlayer1Life();
  }
  /**
   * Protobuf type {@code netGameNodeSDK.gameReport.Status}
   */
  public  static final class Status extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:netGameNodeSDK.gameReport.Status)
      StatusOrBuilder {
    // Use Status.newBuilder() to construct.
    private Status(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Status() {
      player0Life_ = 0;
      player1Life_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Status(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              player0Life_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              player1Life_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mirrorWar.gameReport.GameReport.internal_static_netGameNodeSDK_gameReport_Status_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mirrorWar.gameReport.GameReport.internal_static_netGameNodeSDK_gameReport_Status_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              mirrorWar.gameReport.GameReport.Status.class, mirrorWar.gameReport.GameReport.Status.Builder.class);
    }

    private int bitField0_;
    public static final int PLAYER0LIFE_FIELD_NUMBER = 1;
    private int player0Life_;
    /**
     * <code>required int32 player0Life = 1;</code>
     */
    public boolean hasPlayer0Life() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 player0Life = 1;</code>
     */
    public int getPlayer0Life() {
      return player0Life_;
    }

    public static final int PLAYER1LIFE_FIELD_NUMBER = 2;
    private int player1Life_;
    /**
     * <code>required int32 player1Life = 2;</code>
     */
    public boolean hasPlayer1Life() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 player1Life = 2;</code>
     */
    public int getPlayer1Life() {
      return player1Life_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasPlayer0Life()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPlayer1Life()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, player0Life_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, player1Life_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, player0Life_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, player1Life_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof mirrorWar.gameReport.GameReport.Status)) {
        return super.equals(obj);
      }
      mirrorWar.gameReport.GameReport.Status other = (mirrorWar.gameReport.GameReport.Status) obj;

      boolean result = true;
      result = result && (hasPlayer0Life() == other.hasPlayer0Life());
      if (hasPlayer0Life()) {
        result = result && (getPlayer0Life()
            == other.getPlayer0Life());
      }
      result = result && (hasPlayer1Life() == other.hasPlayer1Life());
      if (hasPlayer1Life()) {
        result = result && (getPlayer1Life()
            == other.getPlayer1Life());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasPlayer0Life()) {
        hash = (37 * hash) + PLAYER0LIFE_FIELD_NUMBER;
        hash = (53 * hash) + getPlayer0Life();
      }
      if (hasPlayer1Life()) {
        hash = (37 * hash) + PLAYER1LIFE_FIELD_NUMBER;
        hash = (53 * hash) + getPlayer1Life();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static mirrorWar.gameReport.GameReport.Status parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mirrorWar.gameReport.GameReport.Status parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mirrorWar.gameReport.GameReport.Status parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mirrorWar.gameReport.GameReport.Status parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mirrorWar.gameReport.GameReport.Status parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mirrorWar.gameReport.GameReport.Status parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static mirrorWar.gameReport.GameReport.Status parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static mirrorWar.gameReport.GameReport.Status parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static mirrorWar.gameReport.GameReport.Status parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mirrorWar.gameReport.GameReport.Status parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(mirrorWar.gameReport.GameReport.Status prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code netGameNodeSDK.gameReport.Status}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:netGameNodeSDK.gameReport.Status)
        mirrorWar.gameReport.GameReport.StatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return mirrorWar.gameReport.GameReport.internal_static_netGameNodeSDK_gameReport_Status_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return mirrorWar.gameReport.GameReport.internal_static_netGameNodeSDK_gameReport_Status_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                mirrorWar.gameReport.GameReport.Status.class, mirrorWar.gameReport.GameReport.Status.Builder.class);
      }

      // Construct using netGameNodeSDK.gameReport.GameReport.Status.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        player0Life_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        player1Life_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return mirrorWar.gameReport.GameReport.internal_static_netGameNodeSDK_gameReport_Status_descriptor;
      }

      public mirrorWar.gameReport.GameReport.Status getDefaultInstanceForType() {
        return mirrorWar.gameReport.GameReport.Status.getDefaultInstance();
      }

      public mirrorWar.gameReport.GameReport.Status build() {
        mirrorWar.gameReport.GameReport.Status result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public mirrorWar.gameReport.GameReport.Status buildPartial() {
        mirrorWar.gameReport.GameReport.Status result = new mirrorWar.gameReport.GameReport.Status(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.player0Life_ = player0Life_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.player1Life_ = player1Life_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof mirrorWar.gameReport.GameReport.Status) {
          return mergeFrom((mirrorWar.gameReport.GameReport.Status)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(mirrorWar.gameReport.GameReport.Status other) {
        if (other == mirrorWar.gameReport.GameReport.Status.getDefaultInstance()) return this;
        if (other.hasPlayer0Life()) {
          setPlayer0Life(other.getPlayer0Life());
        }
        if (other.hasPlayer1Life()) {
          setPlayer1Life(other.getPlayer1Life());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPlayer0Life()) {
          return false;
        }
        if (!hasPlayer1Life()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        mirrorWar.gameReport.GameReport.Status parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (mirrorWar.gameReport.GameReport.Status) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int player0Life_ ;
      /**
       * <code>required int32 player0Life = 1;</code>
       */
      public boolean hasPlayer0Life() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 player0Life = 1;</code>
       */
      public int getPlayer0Life() {
        return player0Life_;
      }
      /**
       * <code>required int32 player0Life = 1;</code>
       */
      public Builder setPlayer0Life(int value) {
        bitField0_ |= 0x00000001;
        player0Life_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 player0Life = 1;</code>
       */
      public Builder clearPlayer0Life() {
        bitField0_ = (bitField0_ & ~0x00000001);
        player0Life_ = 0;
        onChanged();
        return this;
      }

      private int player1Life_ ;
      /**
       * <code>required int32 player1Life = 2;</code>
       */
      public boolean hasPlayer1Life() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 player1Life = 2;</code>
       */
      public int getPlayer1Life() {
        return player1Life_;
      }
      /**
       * <code>required int32 player1Life = 2;</code>
       */
      public Builder setPlayer1Life(int value) {
        bitField0_ |= 0x00000002;
        player1Life_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 player1Life = 2;</code>
       */
      public Builder clearPlayer1Life() {
        bitField0_ = (bitField0_ & ~0x00000002);
        player1Life_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:netGameNodeSDK.gameReport.Status)
    }

    // @@protoc_insertion_point(class_scope:netGameNodeSDK.gameReport.Status)
    private static final mirrorWar.gameReport.GameReport.Status DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new mirrorWar.gameReport.GameReport.Status();
    }

    public static mirrorWar.gameReport.GameReport.Status getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Status>
        PARSER = new com.google.protobuf.AbstractParser<Status>() {
      public Status parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Status(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Status> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Status> getParserForType() {
      return PARSER;
    }

    public mirrorWar.gameReport.GameReport.Status getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_netGameNodeSDK_gameReport_Status_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_netGameNodeSDK_gameReport_Status_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020gameReport.proto\022\031netGameNodeSDK.gameR" +
      "eport\"2\n\006Status\022\023\n\013player0Life\030\001 \002(\005\022\023\n\013" +
      "player1Life\030\002 \002(\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_netGameNodeSDK_gameReport_Status_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_netGameNodeSDK_gameReport_Status_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_netGameNodeSDK_gameReport_Status_descriptor,
        new java.lang.String[] { "Player0Life", "Player1Life", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
